### ISSUE TITLE
Bees changing blocks to other blocks

### ISSUE THREAD

**Issue by Zergmazter** [thedarkcolour/Future-MC#100]
I'm surprised no one has asked about forestry compatibility. While that would probably be too difficult, I think the better option would be to give bees a % to change the block they interact with to another block of our choice via-crafttweaker. 

With this we (the players) could manually build some sort of compatibility with not just forestry, but with many other mods.

**Comment by thedarkcolour** [comment]
Not going to happen. That's not how 1.15 bees work, and I don't feel like it's worth the effort to replace the bee entities in Forestry.
