### ISSUE TITLE
[Suggestion] Add chance for Bee Nests with Bees inside to generate when growing Oak or Birch Saplings near flowers

### ISSUE THREAD

**Issue by NimonoSolenze** [thedarkcolour/Future-MC#101]
According to the Minecraft Wiki, if you grow an Oak or Birch Tree within 2 blocks of a flower, there's about a 5% chance of the tree generating a Bee Nest, which comes with between 1-3 bees. It doesn't appear Future MC has this feature yet; it'd be nice to have it, so it's a bit easier to farm bees without needing to make Bee Hives. Would also help others get them easier, especially when currently they only naturally generate in vanilla biomes.

**Comment by thedarkcolour** [comment]
You can change the biomes that bee nests generate in, and the tree thing uses a coremod so I might not add it this update.

**Comment by thedarkcolour** [comment]
I'll see if I can add it soon.
