### ISSUE TITLE
Bees AI breaking

### ISSUE THREAD

**Issue by StormCircuit** [thedarkcolour/Future-MC#102]
Hey I don't know if it's just my modded install but I noticed bees will sometimes get stuck and halt all motion. I don't know how to help other than to say that it typically happens when they are far away from any flower and it can be fixed simply by bumping into them to make them move or even by holding a flower and getting near them.

I did notice this was an issue in vanilla minecraft here: https://bugs.mojang.com/browse/MC-159350

Let me know if I can do anything else to help.

**Comment by thedarkcolour** [comment]
I'll try to fix it.

**Comment by StormCircuit** [comment]
I figured I would update this: I only noticed this in one dimension. In the overworld they seem to work fine.

**Comment by ridjack** [comment]
This bug exists in vanilla MC as well. 

https://bugs.mojang.com/browse/MC-159350

**Comment by thedarkcolour** [comment]
I've re-implemented the bee AI.
