### ISSUE TITLE
Dispensers do not interact with Bee Nests/Hives

### ISSUE THREAD

**Issue by NimonoSolenze** [thedarkcolour/Future-MC#103]
Dispensers placed facing Bee Nests or Hives cannot be used to automatically harvest honey bottles or honeycomes- they merely eject the bottles or shears no matter the honey level, causing the player to have to manually harvest the honey; vanilla 1.15 allows Dispensers to harvest these things without angering the bees associated with that nest/hive.

**Comment by thedarkcolour** [comment]
I'll fix next update

**Comment by thedarkcolour** [comment]
Fixed in alpha 0.2.01
