### ISSUE TITLE
Baby Bees are Killing Themselves

### ISSUE THREAD

**Issue by TheTennessee** [thedarkcolour/Future-MC#104]
So... seems the baby bees have a relatively short life expectancy. I was having trouble breeding up my bees, and the new bees I bred just... disappeared. I watched one very carefully after a while, and I found that the baby bees were in fact hitting their head on the roof of my garden and doing damage to themselves. Only the baby bees are doing it. I've resorted to a kind of bee breeding den for now, and only releasing them when they are mature.

**Comment by thedarkcolour** [comment]
Bee AI is a bit broken atm. I'll get to this after I fix other issues.
