### ISSUE TITLE
[Bug] Tridents are still broken (but not entirely)

### ISSUE THREAD

**Issue by yezhiyi9670** [thedarkcolour/Future-MC#105]
Trident enchantments does not work. I have tried Impaling, Loyalty and Riptide.4

EDIT: Version is 0.2.02, on Forge 14.23.5.2852.

**Comment by thedarkcolour** [comment]
They only work in the water according to an earlier person. #47

**Comment by yezhiyi9670** [comment]
Loyalty should work out of water according to Minecraft Wiki. Should I open a new issue for this?
