### ISSUE TITLE
[Enhancement] Fix item-using behavior in Creative mode

### ISSUE THREAD

**Issue by yezhiyi9670** [thedarkcolour/Future-MC#107]
As [said on Minecraft Wiki](https://minecraft.gamepedia.com/Creative), an item shouldn't be consumed or changed when a Creative-mode player uses it. The only exception is treated as a bug.

Here's some of the behaviors which need to be fixed:

- Honey bottle. Drinking it duplicates the item, and the count can even exceed the stack limit.
  - Note that sometimes drinking a stack (>1) of honey in Survival Mode will duplicate it Client-only instead of consuming the item
- Campfire. Putting items on the campfire will consume the item in Creative mode. The item in player's inventory is expected to remain.

There may be more.

**Comment by thedarkcolour** [comment]
Thanks for your continuous bug reports!
