### ISSUE TITLE
[1.12.2] Oredict compat for composters

### ISSUE THREAD

**Issue by Sunconure11** [thedarkcolour/Future-MC#108]
Just what it says on the tin

**Comment by thedarkcolour** [comment]
What functions do you need this for at the moment?

**Comment by Sunconure11** [comment]
Honestly, most, if not all of the mod's functions could go with it in some degree.

**Comment by thedarkcolour** [comment]
Certain functions (like the bee pollination targets using IBlockState) don't work with an oredictionary approach. I was hoping your response would mention a few functions in particular.

**Comment by Sunconure11** [comment]
Alright, one thing I was thinking was compost.

**Comment by Sunconure11** [comment]
Yeah, I think the composter would be good. Also kind of why I made this issue in the first place.

**Comment by thedarkcolour** [comment]
Harvestcraft is getting JEI and Harvestcraft compat next update

**Comment by joe-vettek** [comment]
Can more oredict be compatible or configured (more expected)? At present, it is far from enough. For example, Rustic and Cuisine crops are not accepted.

**Comment by thedarkcolour** [comment]
I don't have default values for modded stuff in the composter but I'm open to suggestions

**Comment by democat3457** [comment]
You can also write a simple crafttweaker setup for looping through an oredict and adding to the composter like that

**Comment by thedarkcolour** [comment]
Well, just looked at the Composter... turns out I added OreDict compat at some point for the `addValidItem` function. If I should include it on any other function let me know
