### ISSUE TITLE
[1.12.2] Backport clear water in 1.13

### ISSUE THREAD

**Issue by yezhiyi9670** [thedarkcolour/Future-MC#109]
IMPORTANT: 1.13 did not remove underwater fog, so do not do so. If this is added, make it seperated from water color, which may break water rendering in other mods.

1.13 made changes to the underwater scene, making players able to explore the underwater world better.

1. The water texture has lower opacity. This is already added.
2. Water block (both still and flowing) has lower lighting opacity, making the ocean better lighted. This is already in Optifine, but Optifine's option doesn't work on dedicated servers.  
Implementation Note: If this is turned on, the mod should re-light every chunk when it's loaded, if the chunk is not marked as re-lighted.
3. The underwater scene is always brighter than it was in 1.12.2. The longer the player stays underwater, the longer the view distance will be, and the brighter the scene will be.
4. Respiration enchantment no longer enhances the underwater scene.

EDIT: It seems that the underwater scene is even better in 1.15.2. Backport that one then.

**Comment by thedarkcolour** [comment]
I'll investigate

**Comment by embeddedt** [comment]
FYI, I took over as the maintainer of [Aqua Acrobatics](https://github.com/Fuzss/aquaacrobatics) and this is one of the features I've added in the latest release.

**Comment by thedarkcolour** [comment]
Use Aqua Acrobatics for this feature.
