### ISSUE TITLE
[Minor] Bamboo doesn't have a fuel value.

### ISSUE THREAD

**Issue by BrisingrAerowing** [thedarkcolour/Future-MC#11]
In 1.14 bamboo smelts 0.25 of an item (50 ticks). Could that fuel value be added here?

**Comment by thedarkcolour** [comment]
Oops, sorry about that. Should i release another file, or wait until next update?

**Comment by BrisingrAerowing** [comment]
You can wait. I've used CraftTweaker to add a fuel value to it for now.

**Comment by thedarkcolour** [comment]
Fixed in latest patch
