### ISSUE TITLE
[Bug] Campfire lighting glitches with Optifine

### ISSUE THREAD

**Issue by yezhiyi9670** [thedarkcolour/Future-MC#111]
It seems like the ~~inside~~ textures of the campfire use the same lighting that would apply to the rendering of the outside textures of the same respective face/direction.  
This is not really critical but does certainly look weird.

(Text is copy-pasted from [svenhjol/Charm #51](https://github.com/svenhjol/Charm/issues/51). See this if you don't understand)

![F3 Screenshot](https://i.loli.net/2020/04/10/JSlj2tPHInw8Nmi.png)

**Comment by thedarkcolour** [comment]
This issue also seems to happen with the stonecutter.
