### ISSUE TITLE
Compat issues with BiomeTweaker

### ISSUE THREAD

**Issue by Sunconure11** [thedarkcolour/Future-MC#113]
https://pastebin.com/umMXN7xV

Happens on a server

**Comment by thedarkcolour** [comment]
Disable new water color for now.

**Comment by Sunconure11** [comment]
Had a similar issue pop on another server of mine, turned off the new water color and ran into this:

https://pastebin.com/0tHafhG4

**Comment by thedarkcolour** [comment]
Seems to be a conflicting coremod

**Comment by thedarkcolour** [comment]
I fixed the second crash you sent, it will be in next update

**Comment by thedarkcolour** [comment]
Has the issue been resolved since 0.2.2?

**Comment by thedarkcolour** [comment]
I will be closing this issue if no new information arises.

**Comment by Sunconure11** [comment]
I haven't been able to check, sorry.

**Comment by thedarkcolour** [comment]
I'm just going to close this. Let me know if you need it reopened.
