### ISSUE TITLE
[1.12.2] [Bug] Campfire does not handle CraftTweaked recipes

### ISSUE THREAD

**Issue by yezhiyi9670** [thedarkcolour/Future-MC#116]
There is a CraftTweaker object for tweaking campfire.

I wrote a script to add all furnace recipes which produces food to campfire. The added recipes are displayed in JEI, but they do not function.

(Screenshots are not taken under futuremc-only environment, but this is likely not a compat issue)

Future-MC 1.12.2-0.2.02 · Forge 14.23.5.2852 · Optifine HD_U_F6_pre1

![image](https://user-images.githubusercontent.com/39194383/79035473-a68fd400-7bf1-11ea-85b1-0453dcd0bb0a.png)

▲ The recipe is displayed properly

![image](https://user-images.githubusercontent.com/39194383/79035485-c626fc80-7bf1-11ea-986f-bdbc48fc8f94.png)

▲ CraftTweaked recipes work properly in Smoker

![image](https://user-images.githubusercontent.com/39194383/79035535-23bb4900-7bf2-11ea-9549-768e70c7206d.png)

▲ Campfire does not accept CraftTweaked items

**Comment by thedarkcolour** [comment]
You know what? I might be able to add some sort of automatic meat adding function.
