### ISSUE TITLE
[1.15.2] Custom pack will boot on client, not on server.

### ISSUE THREAD

**Issue by ridjack** [thedarkcolour/Future-MC#118]
As the title says; with FutureMC installed, my server simply refuses to boot, giving the error message you can see in the Gist below.

I double-checked I had the latest 'Kotlin for Forge' version, and I updated Forge to the latest version to try that. Nothing made a difference.

To test the client, I deleted all of the mods there and used only the server's mods. The game started with no problems, although I did not attempt to load a world. 

https://gist.github.com/ridjack/4b2b325b74304b726f3f2f66e32c52b1

**Comment by thedarkcolour** [comment]
Fixing next update.

**Comment by thedarkcolour** [comment]
Fixed in 1.0.1
