### ISSUE TITLE
Crash between – Foam fix, Iguana Tweaks and Future MC

### ISSUE THREAD

**Issue by Pseudohuman93** [thedarkcolour/Future-MC#12]
Hello,
There seems to be an issue with three mods.
I’m reporting to all of them so they can be aware of the issue.
Thanks, in advanced to all of them for their response.
This is the crash log:
-	https://paste.dimdev.org/puzivusugu.mccrash
The crash happens when I start Minecraft.
(You may want to talk to each other to avoid compatibility issues)

**Comment by thedarkcolour** [comment]
Try disabling loom in the config options of my mod.

**Comment by thedarkcolour** [comment]
Try using the latest version of my mod.

**Comment by thedarkcolour** [comment]
I just tried to reproduce, I finally fixed it! Thanks for your help.
