### ISSUE TITLE
[1.12.2] Trapdoors do not have recipes

### ISSUE THREAD

**Issue by thedarkcolour** [thedarkcolour/Future-MC#127]

**Comment by MrJake222** [comment]
When you plan to fix this? Because I plan on doing a pull request for this one ;)

**Comment by thedarkcolour** [comment]
Upcoming fix means I've already fixed it and it's on hold because of other bugs/features

**Comment by MrJake222** [comment]
So like cannot you just push your changes so I can clone and build for personal use? Or are they pushed already?

**Comment by MrJake222** [comment]
And I also believe there is a conflict with Nether brick walls and Nether brick fences.

**Comment by thedarkcolour** [comment]
I tend to not push changes until an update comes out, but there are jars on my discord server that have the fix.

**Comment by thedarkcolour** [comment]
If you'd just like the link, here it is: [https://cdn.discordapp.com/attachments/706297191672840234/707745056475316314/future-mc-1.12.2-0.2.03.jar](url)

**Comment by MrJake222** [comment]
Ughh I don't think it's fixed, at least in my modpack. The JEI shows `accept any: plankWood` and crafting trapdoors still always yelds the same Oak trapdoor
