### ISSUE TITLE
[1.12.2] cascading worldgen lag

### ISSUE THREAD

**Issue by HeberonYT** [thedarkcolour/Future-MC#128]
The latest versions of FutureMC are using cascading generation, which forge doesn't like and causes TPS drops.
![Screenshot_8](https://user-images.githubusercontent.com/13698597/80297261-2ae06c00-8747-11ea-847e-04f5c76a8f32.png)

I suggest changing the method used for the world generation.
some tips can be read in this article.

https://www.minecraftforge.net/forum/topic/66764-1122what-is-wrong-with-my-worldgen/

**Comment by thedarkcolour** [comment]
The issue was that I used incorrect bit shifts when porting from java to kotlin (typo). It's getting fixed next version.
