### ISSUE TITLE
[1.12.2] Campfire throws cooked food around

### ISSUE THREAD

**Issue by zakerunner** [thedarkcolour/Future-MC#129]
I don't know if this is vanilla 1.14 behavior or not, but when food is done cooking it gets thrown in a random direction instead of toward the player, and sometimes the food goes missing.

**Comment by yezhiyi9670** [comment]
It's intended that campfire throws cooked food around (can be seen in 1.14+). Maybe you should add more information about despawning food after cooking.

**Comment by thedarkcolour** [comment]
What version of Future MC are you running

**Comment by thedarkcolour** [comment]
I'm going to close this issue if nobody else can answer here.

**Comment by thedarkcolour** [comment]
Closed because of inactivity
