### ISSUE TITLE
Slime blocks not sticking to each other (at least not moving blocks)

### ISSUE THREAD

**Issue by MrJake222** [thedarkcolour/Future-MC#130]
> Tested with `future-mc-1.12.2-0.2.02` and `Forgelin-1.8.2`

Trying to move 2 rows of blocks with one piston causes this(bottom iron blocks don't get moved):
![2020-04-29_23 04 14](https://user-images.githubusercontent.com/7581790/80646988-06013700-8a6e-11ea-96a0-3d8b783f1dea.png)

**Vanilla behaviour:**
![2020-04-29_23 04 54](https://user-images.githubusercontent.com/7581790/80647009-0d284500-8a6e-11ea-9a8a-a91185c8358e.png)

**Comment by thedarkcolour** [comment]
Same code issue as #126
