### ISSUE TITLE
Fish spawn rate

### ISSUE THREAD

**Issue by steve13689** [thedarkcolour/Future-MC#137]
Future MC 1.12.2 0.2.02 in an ocean biome with b.o.p installed thousands of fish spawn in a very small area as soon as you get near the water, if you jump in so many spawn the computer starts to freezeframe and all you can see is fish. render distance of 8 and there must be close to 100,000 fish on screen with a ratio of 2:1 cod to salmon. You look in from a hill and the ocean is just fish. Had to disable fish in the config as the server was unusable due to lag. I'm surprised nobody else has come across this.

**Comment by thedarkcolour** [comment]
People have experienced this, but I haven't found a solution for it.

**Comment by steve13689** [comment]
No problem I installed 'in control' and have configured the spawn rate through that I reduced it to 15 per chunk per player. And it seems about right now. I have noticed that no items drop when killing the fish and when listing all items from your mod there are no items for the fish apart from the fish in buckets was this an error? Or were they not supposed to drop anything?

Thanks for getting back to me I love the mod I've installed it for as long as I can remember on my personal server thankyou for all your effort.

**Comment by thedarkcolour** [comment]
I forgot to add their drops.

**Comment by thedarkcolour** [comment]
Although I have seen the bug first hand, it seems that I can no longer reproduce it. I'm thinking it's a certain combination of mods that cause it, but I tested with my personal modpack and fish were spawning normally.

**Comment by border999** [comment]
I'm having the same issue, and I use cubic chunks... along with about 400 other mods but this mod spawn so many fish it kills my fps /killing all these fish is murder on my system in and of itself.

**Comment by steve13689** [comment]
As a temporary fix the mod 'in control' worked perfect to reduce the spawn rate I also configured the loot drops so everything works correctly now. If you would like i can send you a copy of the config files for it that i have made to get you on until the bugs are worked out in this mod. Steve

**Comment by border999** [comment]
@steve13689 yes please

**Comment by steve13689** [comment]
No problem mate heres my configs and the mod im using if you have any issues or cant download the files let me know.

https://drive.google.com/folderview?id=1--B_6_JOX6E_J3TAYMuIdfaxuUdLdX0M

**Comment by operamaniac** [comment]
Hey, I've experienced this same issue, I have less than 30 mods when this happen so this might help you to find the cause : https://pastebin.com/8khV7W5i

**Comment by Landsurfer2000** [comment]
massive fish spawn rate is caused by randomtweaks, unsure what about it causes the massive spawn rate but my guess is something to do with the squid tweaks done to it. randomtweaks is opensource which is good though

**Comment by BrisingrAerowing** [comment]
I've linked this over to the Random Tweaks repo.

**Comment by TheRandomLabs** [comment]
The squid spawning tweaks specifically only touch entities of the `EntitySquid` class, so I'm not sure if that's the problem. Regardless, does the issue persist when the squid spawning tweaks are disabled? (Set `maxPackSize` and `spawnRadiusLimit` to `0`)

**Comment by Kenja-mc** [comment]
I encountered the same problem on a pack with RandomTweaks and Future MC plus various other mods. 

**I can confirm that setting `maxPackSize` and `spawnRadiusLimit` to `0` did fix the issue for us.**

However I will say that after runnning LagGoggles, there are still too many tropical fish entities ticking on the server to my liking, so it would be nice if FutureMC had per chunk per player spawn limits for the fish by default.

**Comment by Blue-Beaker** [comment]
Too many fishes lags my internal server, so I have to reduce fish spawn rate until it has been fixed.
A spawn cap for fishes is absolutely needed.

**Comment by MusicMaestro123** [comment]
And a separate spawn cap for squid as well just like in 1.16.

**Comment by thedarkcolour** [comment]
There is a config option for fish spawnrate @Blue-Beaker

**Comment by BrisingrAerowing** [comment]
Further investigation shows that turning off Random Tweaks squid changes has no effect on fish spawn rates. I'm still getting hundreds of fish in an area.

**Comment by Kenja-mc** [comment]
Sorry if my post was misleading, I realize now that as I was uploading the config for the server, my friend uploaded an InControl file to limit the spawn rate at the same time, and because of that I thought the RT config tweak fixed it.

Sorry about that.

**Comment by BrisingrAerowing** [comment]
There are several issues on the In Control repo about it seeming to cause mob spam. I'm starting to think this may be a Vanilla issue that is being triggered by certain mods that manipulate spawn rules.

**Comment by thedarkcolour** [comment]
I have found a janky solution.
