### ISSUE TITLE
Smiting Table and Cartography Table Gui Crash [1.12.2]

### ISSUE THREAD

**Issue by TBiscuit1** [thedarkcolour/Future-MC#138]
For the Cartography Table, it's not really implemented yet, there is still no texture and you can't craft it so it's understandable that it crash

For the Smiting Table though, it tries to open the gui but the gui only exist in 1.15 so game crash, (happily, I had vanilla fix and it just closed the game and said that it would have crashed)

**Comment by thedarkcolour** [comment]
Both aren't supposed to be implemented. I think you can change the functionality option for smithing table in config.
