### ISSUE TITLE
barrel can copy items

### ISSUE THREAD

**Issue by i493052739** [thedarkcolour/Future-MC#141]
There is a Bug that can duplicate items in a barrel... 
when a player opens a barrel's GUI, then another player breaks the barrel, it occurs...

the first player still have the GUI, but the second player can pick up all the items dropped from the barrel

**Comment by SanjivanM** [comment]
Try removing the items from the GUI, they might be "ghost" items and disappear after MC realizes that those items were dropped/ picked up already

**Comment by i493052739** [comment]
You can retest it... I remember that they could be combined together... So it's a better way to close the GUI when block is broken by others.

**Comment by thedarkcolour** [comment]
Figured it out ty for reporting
