### ISSUE TITLE
It's Back: Beetroot Crop Problem

### ISSUE THREAD

**Issue by TheTennessee** [thedarkcolour/Future-MC#142]
I just got another crash after finally putting my beetroots back in. It seems that the problem still exists. I did update to the newest version, and yet I am still getting the crash.

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in BlockStateContainer{block=minecraft:beetroots, properties=[age]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:209)
    at thedarkcolour.futuremc.api.BeePollinationHandler$Companion$$special$$inlined$create$2.pollinateCrop(BeePollinationHandler.kt:121)
    at thedarkcolour.futuremc.entity.bee.EntityBee$AIGrowCrops.updateTask(EntityBee.java:594)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:888)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at thedarkcolour.futuremc.entity.bee.EntityBee.onLivingUpdate(EntityBee.java:296)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at thedarkcolour.futuremc.entity.bee.EntityBee.onUpdate(EntityBee.java:183)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$updateEntity$zbo000(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

**Comment by thedarkcolour** [comment]
I've figured it out. The wheat and beetroot age properties were mixed up.

**Comment by TheTennessee** [comment]
Ah, awesome. Glad you found it.

**Comment by DrainedLmao** [comment]
hey im constantly getting this crash every few mins and after i delete the minecraft regions and load my world back up i dont crash anymore for a little bit unless i go exploring and i cannot for the life of me find any type of fix, but you did state there that you fixed it because of the age properties? unsure what that is but how can i fix? also heres my crash report if it helps   





---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/14/22, 5:47 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot set property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} to 4 on Block{minecraft:beetroots}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:125)
	at net.minecraft.class_2302.method_9828(class_2302.java:67)
	at net.minecraft.class_2302.handler$bim000$randomTick(class_2302.java:1035)
	at net.minecraft.class_2302.method_9514(class_2302.java)
	at net.minecraft.class_2242.method_9514(class_2242.java:52)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:921)
	at net.minecraft.class_3218.redirect$dhj000$redirectBlockStateTick(class_3218.java:10669)
	at net.minecraft.class_3218.method_18203(class_3218.java:483)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:325)
	at net.minecraft.class_3218.method_18765(class_3218.java:308)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11657(class_2688.java:125)
	at net.minecraft.class_2302.method_9828(class_2302.java:67)
	at net.minecraft.class_2302.handler$bim000$randomTick(class_2302.java:1035)
	at net.minecraft.class_2302.method_9514(class_2302.java)
	at net.minecraft.class_2242.method_9514(class_2242.java:52)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:921)
	at net.minecraft.class_3218.redirect$dhj000$redirectBlockStateTick(class_3218.java:10669)
	at net.minecraft.class_3218.method_18203(class_3218.java:483)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:325)
	at net.minecraft.class_3218.method_18765(class_3218.java:308)

-- Affected level --
Details:
	All players: 2 total; [class_3222['DrainedLegacy'/756, l='ServerLevel[Island World]', x=106.77, y=84.00, z=-31.22], class_3222['DevoidxD'/924, l='ServerLevel[Island World]', x=108.23, y=73.02, z=-140.10]]
	Chunk stats: 2711
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,68,0), Section: (at 0,4,0 in 1,4,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 601773 game time, 600029 day time
	Level name: Island World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 19263 (now: true), thunder time: 78078 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 474844136 bytes (452 MiB) / 4315938816 bytes (4116 MiB) up to 8556380160 bytes (8160 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b06
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 27382.75
	Virtual memory used (MB): 23654.17
	Swap memory total (MB): 11075.14
	Swap memory used (MB): 788.98
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8160m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 2.2.1
		adorn: Adorn 3.1.0+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.4.6
		airhop: Air Hop 3.1.1
		amecsapi: Amecs API 1.3.2+mc1.18-pre1
		amplified_nether: Amplified Nether for Fabric 1.0.1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.1
		animatica: Animatica 0.2+1.18
		aqupdcaracal: Caracal mob 1.18-1.3.5.1
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.1
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 3.4.9
		attributefix: AttributeFix 13.0.3
		axolotlitemfix: Axolotl Item Fix 1.1.3
		backslot: BackSlot 1.2.3
		backslotaddon: BackSlot Addon 1.0.7
		balm-fabric: Balm 2.4.0+0
		basicshields: Basic Shields [Fabric] 1.1.1-1.18.1
		bcc: BetterCompatibilityChecker fabric-1.0.4
		bclib: BCLib 1.2.1
		beehivetooltips: Beehive Tooltips 1.4.1
		beenfo: Beenfo 1.18.1-fabric0.45.0-1.3.3
		better_wandering_trader: Better Wandering Trader 1.8.0
		betterend: Better End 1.0.0
		betterf3: BetterF3 1.2.2
		betternether: Better Nether 6.0.8
		betterpingdisplay: Better Ping Display 1.1.1
		bettersleeping: BetterSleeping 0.5.1+1.18
		betterthirdperson: Better Third Person 1.6.0
		blockus: Blockus 2.3.4+1.18.1
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.3-1.18
		bountiful: Bountiful 2.0.1
		bowyery: MK's Bowyery 1.0.0-1.18.1
		breakprogress: Break Progress 1.0.1
		campchair: Camp Chair 1.0.0
		capybara: Capybara 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carrier: Carrier 1.9.0
		chat_heads: Chat Heads 0.6.0
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		clickadv: Clickable Advancements Mod 2.1
		clienttweaks: Client Tweaks 7.0.0
		climbladdersfast: ClimbLaddersFast 2.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		clumps: Clumps 8.0.4
		coat: Coat 1.0.0-beta.15
		collective-fabric: Collective (Fabric) 4.9
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.0.0-1.18
		companion: Companion 1.1.0
		consistency_plus: Consistency Plus 0.4.3+1.18
		continuity: Continuity 1.0.3+1.18
		controlling: Controlling For Fabric 9.0.8
		cosmetica: Cosmetica 0.3.2
		crawl: Crawl 0.10.0
		creatures_of_the_jungle: Creatures From The Jungle 1.0.0
		crops_love_rain: Crops Love Rain 1.2.1
		crowdin-translate: CrowdinTranslate 1.4+1.18
		custom-crosshair-mod: Custom Crosshair Mod 1.3.8-fabric
		dark-enchanting: Dark Enchanting 0.6.3+1.18
		darkpaintings: DarkPaintings 9.0.2
		dashloader: DashLoader 3.1.1+1.18
		dawn: Dawn API 3.2.0
		daylight_mobs_reborn: Daylight Mobs Reborn 1.2.3
		deathlog: DeathLog 0.2.4+1.18
		deepslatecutting: Deepslate Cutting 1.3.0
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.4.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		disenchanter: Disenchanter 0.1.4+1.18
		dragonloot: DragonLoot 1.0.9
		drippyloadingscreen: Drippy Loading Screen 1.4.2
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dungeons_arise: When Dungeons Arise 2.1.49c-fabric
		dynview: Dynamic View Mod 1.18-1.5
		earthtojavamobs: Earth2Java 1.7.4+1.18
		easymagic: Easy Magic 3.2.1
		eatinganimationid: Eating Animation 1.2
		effective: Effective 1.1
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchantedtooltips: Enchanted ToolTips 1.3.5-1.18
		enchantment_lore: Enchantment Lore 1.2.3+MC1.18-1.18.1
		enchdesc: EnchantmentDescriptions 9.0.7
		endgoblintraders: End Goblin Traders 1.4.2
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.18
		enhancedcelestials: Enhanced Celestials 2.0.6
		entityculling: EntityCulling-Fabric 1.5.0
		equipmentcompare: Equipment Compare 1.2.9
		exenchants: Extended Enchantments 0.0.4
		expcontainer: Experience Container [XP] 1.15.3
		experiencebottler: Experience Bottler 1.18.1+build.1
		experiencebugfix: Experience Bug Fix 18
		fabric: Fabric API 0.46.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33514
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.10+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.13+b0b66fc365
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.0+1254045365
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.0+0a73a6c265
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fabricshieldlib: Fabric Shield Lib 1.4.5-1.18
		fake-player-api: Fake Player API 0.3.0
		fallingleaves: Falling Leaves 1.8.1+1.18.1
		fallingtree: FallingTree 2.16.1
		fancymenu: FancyMenu 2.4.3
		fastfurnace: FastFurnace 1.18-4
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric $version
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		fireworkfrenzy: Firework Frenzy 1.7
		fishofthieves: Fish of Thieves 1.0.0
		floral_flair: Floral Flair 1.1.0
		forgeconfigapiport: Forge Config API Port 3.1.0
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		fortune-gives-experience: Fortune Gives Experience 1.1.0
		friendsandfoes: Friends&Foes 1.0.2
		gbfabrictools: GBfabrictools 1.3.4+1.18
		geckolib3: Geckolib 3.0.23
		geodes: More Geodes 1.2.0
		go-fish: Go Fish 1.4.1-1.18.1
		goblintraders: Goblin Traders 1.4.1
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.1
		guardvillagers: Guard Villagers Fabric 1.0.7
		guild: Guild 0.3.6
		heartbond: Heartbond 1.2.0
		highlighter: Highlighter 1.1.2
		horseinfo: Horse Info 0.4.1-1.18
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		iceberg: Iceberg 1.0.27
		illuminations: Illuminations 1.10.2
		indium: Indium 1.0.2-alpha1+mc1.18
		infusion_table: Infusion Table 1.0.5
		inmis: Inmis 2.4.0-1.18
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.1.4
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 3.0.0
		kiwi: Kiwi 5.2.2
		kleeslabs: KleeSlabs 11.0.0
		konkrete: Konkrete 1.3.2
		krypton: Krypton 0.1.6
		kyrptconfig: Kyrpt Config 1.2.6-1.18
		lambdabettergrass: LambdaBetterGrass 1.2.2+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.2.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		lithium: Lithium 0.7.6
		lovely_snails: Lovely Snails 1.0.3+1.18
		lushforest: Lush Forests 1.2.0
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		mavm: More Axolotl Variants Mod 1.0.7a
		maybe-more-data: Maybe More Data 1.0.0-1.18
		mca: Minecraft Comes Alive 7.2.1+1.18.1
		me_hypherionmc_simple-rpc-common: simple-rpc-common 1.0.15
		megane: megane 6.2.0
		megane-base: megane-base 6.2.0
		megane-fabric-transfer: megane-fabric-transfer 6.2.0+1.5.4-b4f4f6cda9
		megane-runtime: megane-runtime 6.2.0
		megane-vanilla: megane-vanilla 6.2.0+1.18.1
		midnightlib: MidnightLib 0.3.1
		milk: Milk Lib 0.1.3
		milk_plus: Milk+ 2.0.0
		minecraft: Minecraft 1.18.1
		minieffects: Mini Effects 4.0.0
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		more-axolotls: More Axolotls 1.0.2
		morebannerfeatures: More Banner Features 1.1.3
		morerespawnanchors: More Respawn Anchors 1.0.3
		morevillagers-fabric: MoreVillagersFabric 3.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousetweaks: Mouse Tweaks 2.20
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		nears: Nears 1.1.2
		no-telemetry: No Telemetry 1.3.0
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		notes: Notes 1.0.9
		numismatic-overhaul: Numismatic Overhaul 0.1.8+1.18
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.1.0
		onsoulfire: On Soul Fire 1.18-1
		openloader: OpenLoader 11.0.3
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-text: commons-text 1.9
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		owo: oωo 0.5.2+1.18
		oxidized: Oxidized 1.5.2
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		paintings: Paintings++ 1.0.0.6
		patchouli: Patchouli 1.18.1-63-FABRIC
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 3.1.0
		plushies: Plushie Mod 1.1
		polymorph: Polymorph 0.0.16-1.18.1
		pride: Pride Lib 1.1.0+1.17
		puzzleslib: Puzzles Lib 3.2.1
		quartzelv: Quartz Elevator 2.0.1+1.18
		quickshulker: Quick Shulker 1.3.1-1.18
		rad: Reload Audio Driver 1.0.1
		repurposed_structures: Repurposed Structures 3.1.13+1.18.1
		rocks: This Rocks! 1.5.2
		roughlyenoughitems: Roughly Enough Items 7.1.357
		roughlyenoughresources: Roughly Enough Resources 2.3.0
		rpgstats: RPGStats 4.3.5+1.18.1
		runelic: Runelic 10.0.1
		satin: Satin 1.7.0
		sculk_worm: Sculk Worm 0.1.3
		seasons: Fabric Seasons 1.3-BETA+1.18
		seedfix: Seed Fix 1.0.0
		sentimentality3: Sentimentality 3 1.3.6
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		shulkerutils: shulkerutils 1.0.4-1.18
		silktouch_spawners: SilkTouch Spawners 0.0.1
		simple-rpc: Simple Rpc 2.7
		skinlayers: 3d Skin Layers 1.3.1
		skinnedlanterns: Skinned Lanterns 1.2.0+build.12
		skylorlib: SkyLib 1.0.6
		snowpig: Snow Pig 1.0.0+build.33
		snowrealmagic: Snow! Real Magic! 3.1.0
		soaringstructures2: Soaring Structures 2 1.18 - 2.2
		sodium: Sodium 0.4.0-alpha5+build.9
		someforgepatchesported: Some Forge Patches Ported 1.0.2
		spark: spark 1.7.1
		spruceui: SpruceUI 3.3.2+1.17
		stacc: Stacc 1.3.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
		stoneholm: Stoneholm 1.4.1
		subterrestrial: Subterrestrial 1.0.1
		terrablender: TerraBlender 1.1.0.77
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		the_bumblezone: The Bumblezone - Fabric 4.1.1+1.18.1
		thonkutil: ThonkUtil 2.6.0+1.18
		thonkutil-base: ThonkUtil Base 1.4.0+6a7a08aec8
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.2.0+a46c8f89c8
		thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.6+6a7a08aec8
		thonkutil-customization: ThonkUtil Customization (v1) 1.0.1+6a7a08aec8
		thonkutil-legacy: ThonkUtil Legacy 1.0.7+6fa117f8c8
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.2.5+6a7a08aec8
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.5+6a7a08aec8
		tinyskeletons: Tiny Skeletons 3.1.0
		toms_storage: Tom's Simple Storage Mod 1.1.19
		toolstats: ToolStats 8.0.1
		tooltipfix: ToolTip Fix 1.0.4-1.18
		torchbowmod: TorchBowMod 1.0
		totw_additions: Towers of the Wild: Additions 1.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.0
		tradingpost: Trading Post 3.1.2
		transportables: Transportables 1.1
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.1.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.2
		twigs: Twigs 1.1.2
		twm: The Wild Mod 0.2
		universal_ores: Universal Ores 1.2.1
		unvotedandshelved: Unvoted & Shelved 1.0.4
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.18
		urns: Urns 1.0.1
		vanilla_degus: Vanilla Degus 1.3.0
		veinmining: Vein Mining 0.0.11-1.18
		villager-hats: Villager Hats Mod 1.2.1
		villagernames: Villager Names 2.0.2
		villagersleashed: Villagers Leasged 1.0
		visuality: Visuality 0.4.0
		visualworkbench: Visual Workbench 3.1.0
		voidtotem: VoidTotem (Fabric) 1.18.1-1.1.0
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.0.3+mc1.18-rc3
		waystones: Waystones 2.4.1
		wmitaf: WMITAF 2.2.0
		wthit: wthit 4.4.0
		xaerominimap: Xaero's Minimap 21.23.0
		xaeroworldmap: Xaero's World Map 1.19.0
		xlpackets: XLPackets 2.1-1.17.1
		xp_storage: XP Storage 1.4.3+1.18
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.18
		yigd: You're in Grave Danger 1.2.10
	Server Running: true
	Player Count: 2 / 8; [class_3222['DrainedLegacy'/756, l='ServerLevel[Island World]', x=106.77, y=84.00, z=-31.22], class_3222['DevoidxD'/924, l='ServerLevel[Island World]', x=108.23, y=73.02, z=-140.10]]
	Data Packs: vanilla, Fabric Mods, data/Repurposed_Structures-More_Villagers_v3.zip, data/ichphilipp-s-endcity-v1-1-1-16-2.zip (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
