### ISSUE TITLE
[1.12.2] Using shears from a dispenser on a hive results in the shears dispensing alongside the output

### ISSUE THREAD

**Issue by Landiie** [thedarkcolour/Future-MC#155]
visual:
![ezgif com-optimize](https://user-images.githubusercontent.com/43101146/84334240-c2a6e780-ab46-11ea-9423-26be48d9dd86.gif)

**Comment by thedarkcolour** [comment]
Gonna try to fix this and the honey bottle one before a release.

**Comment by thedarkcolour** [comment]
Sorry for the late fix, I just figured it out
