### ISSUE TITLE
[1.12.2] Ancient Debris doesn't generate at negative coordinates

### ISSUE THREAD

**Issue by sailent704** [thedarkcolour/Future-MC#159]
Hi, I've been running a server with the latest FutureMC version for a while now, and after countless hours of searching for Ancient Debris, I found none. I tried looking for it with Future's wallhack, and I got to the conclusion that the Ancient Debris block doesn't generate.
I double-checked if Netherite wasn't disabled in the config file on the server, which it isn't;
I tried reproducing the bug in SinglePlayer, and managed to find a probable cause. Ancient Debris **does** generate near 0, 0 in the Nether, however, it doesn't generate anywhere else.
As you can see on the screenshot with no Ancient Debris, I'm far out on the Z axis.
If I go to those approximate coordinates with my Z coordinate being close to 0, it **does** actually generate, as you can see from the screenshot.

Hence, if I go far out on both axis, my chance of getting Netherite is 0, because no Ancient Debris generates.

The server console is hinting toward this being a problem, as when generating new chunks, FutureMC seems to populate the wrong chunks.

![FML Console Log showing warnings](https://user-images.githubusercontent.com/61205459/84869258-1604c280-b07e-11ea-989b-0e89ad0bd742.png)

(Server) Mod List: https://pastebin.com/FUsb2K2u

![Far on both axis - no Ancient Debris generated](https://user-images.githubusercontent.com/61205459/84836528-3446d000-b036-11ea-90ce-faf5273e2a25.png)
![Ancient Debris generated with Z close to 0](https://user-images.githubusercontent.com/61205459/84868891-a1318880-b07d-11ea-9f1c-58d73eb5e168.png)
![Ancient Debris not generating anywhere else](https://user-images.githubusercontent.com/61205459/84868972-bd352a00-b07d-11ea-9aba-cfd32ccbd117.png)

**Comment by thedarkcolour** [comment]
I don't remember encountering this in my own modpack. I've only found two ancient debris, and it generated normally.

**Comment by sailent704** [comment]
I'll try to find which mod in particular is causing it, but since it's really late for me, this issue has to wait for ~18 hours.

**Comment by DemonfangArun** [comment]
version: 0.2.3.2
forge: x.2854

While I'm not getting the same console errors as OP, I do believe that it isn't generating right. While it is more rare than diamond, I should find one within 10 minutes of searching with an endgame pick that instabreaks most everything.

I'd also like to add in that it would be a good idea to add a configurable rate in for this. While netherite is endgame in vanilla it's not so much in a heavy modpack. I can easily get cobalt and ardite which make far better gear then netherite.

**Comment by sailent704** [comment]
I took to recompiling the mod myself because of this. I severely buffed Netherite, as it's supposed to be better than Obsidian Armor IMO.

**Comment by DemonfangArun** [comment]
That could be it. I use OTG and biome bundle, and although it doesn't touch the nether (afaik) there's certainly room there for problems. It's also possible that all the other ores generating in the nether in my pack are giving it a hard time, which could also be helped with a configurable rate.

**Comment by thedarkcolour** [comment]
Forgot about netherite not being correct whoops

**Comment by sailent704** [comment]
I'd also welcome adjustable settings for Netherite tools / armor, because recompiling the mod just because of an armor buff is really annoying.

**Comment by DemonfangArun** [comment]
Upon further inspection, nothing netherite can be crafted.

**Comment by sailent704** [comment]
I also cannot craft anything from Netherite. This is easily fixed with a Craft Tweaker script, but it would certainly be nice if it worked out of the box.

**Comment by DemonfangArun** [comment]
-Reads up on the mechanics- ok, so you use the smithing table to upgrade to netherite. That's what I get for not looking into vanilla :P

**Comment by thedarkcolour** [comment]
Use the smithing table :)

**Comment by thedarkcolour** [comment]
I'm going to close this if there's no information you can offer.

**Comment by thedarkcolour** [comment]
What specific mod causes this?

**Comment by sailent704** [comment]
It seems to be BoP or any other mods that change the vanilla generation.

**Comment by Aeron216** [comment]
Can confirm that there is a complete absence of Ancient Debris in the Nether while having BoP and NetherEx in the same pack.

**Comment by SanaKitty** [comment]
Can also confirm getting this issue in a pack that has BoP. Seems to only generate ~7 blocks either size of z0.

**Comment by AWConant** [comment]
OTG/Biome Bundle/Quark user here, no Ancient Debris anywhere, as far as I can tell.

**Comment by thedarkcolour** [comment]
Specific behavior is that ore cannot spawn at coordinates that are not positive.

**Comment by AWConant** [comment]
If that's a bug with pure Future MC, I suspect a separate issue should be opened re: Debris not generating anywhere when paired with generation mods like BoP/BB.

**Comment by thedarkcolour** [comment]
@AWConant if you are still having issues with a newly generated world with latest future mc open a separate issue
