### ISSUE TITLE
[1.12.2] Crashing during runtime deobfuscation

### ISSUE THREAD

**Issue by ChesterS1** [thedarkcolour/Future-MC#160]
The mod keeps crashing me for no reason and it's not leaving a crash report either. Please help!

**Comment by thedarkcolour** [comment]
Install forgelin

**Comment by Alee-OneHit** [comment]
use SecurityCraft v1.8.18.2 ?

**Comment by thedarkcolour** [comment]
Can't reproduce

**Comment by thedarkcolour** [comment]
If you can't give me info/crash log I'm going to close the issue
