### ISSUE TITLE
[1.12.2] FutureMC problem with Securitycraft 

### ISSUE THREAD

**Issue by Alee-OneHit** [thedarkcolour/Future-MC#162]
Since I updated the SecurityCraft, I started having crash problems on my server and disconnection of my users, there must be some entity problem with the FutureMC mod, then I leave the crash log you already update the 2 mods and still keep this problem;

(SecurityCraft v1.8.18.2) 
https://pastebin.com/Bvsp5BN7

**Comment by Alee-OneHit** [comment]
The creator of Securitycraft tells me that it is a problem that iron_mine detects as a block of futuremc and that is why there are problems there will be a solution!

**Comment by thedarkcolour** [comment]
What are you doing that ends in the crash?

**Comment by Alee-OneHit** [comment]
nothing just put the latest version of securitycraft and futuremc, I thought it was the version of future so I went back to a previous beta that worked perfectly, but it is the same, it gives the error that a block of the futuremc counts it as securitycraft .. .

**Comment by Alee-OneHit** [comment]
and have solution ??'

**Comment by thedarkcolour** [comment]
I cannot reproduce this, but I did discover that the taser crashes the game when you use it.

**Comment by thedarkcolour** [comment]
I'm going to close this if you don't have any extra info about what how the crash occurs
