### ISSUE TITLE
[1.12.2] Bee Breeding

### ISSUE THREAD

**Issue by MusicMaestro123** [thedarkcolour/Future-MC#166]
Would like to be able to breed bees with any flower of course this will use the Ore Dictionary and use any "flower". Just a quality of life thing really.

**Comment by thedarkcolour** [comment]
Add them through CraftTweaker for now

**Comment by thedarkcolour** [comment]
After looking into a few mods I have found that only a few mods actually use the "flower" OreDictionary tag so it take more than just an OreDictionary tag. I do have a few mod's flowers added by default though!

**Comment by thedarkcolour** [comment]
"flower" isn't a forge OreDictionary tag. Not all mods support it so I'm just gonna rely on adding them manually
