### ISSUE TITLE
[1.12.2] SmithingTable - JEI integration and Crafttweaker

### ISSUE THREAD

**Issue by thewawpro** [thedarkcolour/Future-MC#171]
No jei support for the smithing table.

The smithing table doesn't work with tags like this..
mods.futuremc.SmithingTable.addRecipe(tool, <quark:diamond_heart>, tool.withTag({Unbreakable: 1}));

**Comment by thedarkcolour** [comment]
JEI integration is coming for Composter and Smithing Table
