### ISSUE TITLE
Grindstone doesn't disenchants items if we don't repair item...

### ISSUE THREAD

**Issue by Fireztonez** [thedarkcolour/Future-MC#18]
Hello, I have try the grindstone added by Future-MC, it work great for repairing stuff, but when this is question to disenchant, it only work if you place 2 items at the same time question of repairing the tool. I just test in Minecraft Vanilla 1.14 question to make sure how it work exactly (Because I only play modded minecraft for long time) and the grindstone can totally disenchant any items whiteout repairing.

Version:
FutureMC: 0.1.5c
Forge: 14.23.5.2838

Thank's for your great mod, continue your good work!
Fireztonez

**Comment by thedarkcolour** [comment]
Working on a fix rn.

**Comment by thedarkcolour** [comment]
Fixed in 0.1.6
