### ISSUE TITLE
[1.12.2] Fish spawning in huge numbers issue still persists

### ISSUE THREAD

**Issue by Unhook** [thedarkcolour/Future-MC#180]
Latest update was said to fix fish spawning in insane numbers. Yet they still spawn in insane numbers in version 2.4.0pre

Modlist: https://pastebin.com/K6ZZCVPs

**Comment by thedarkcolour** [comment]
Mod list paste isn't loading?

**Comment by thedarkcolour** [comment]
Perhaps it's random patches that causes it...

**Comment by thedarkcolour** [comment]
Let me know if the new jar fixes it. If you don't respond I'll just close this issue.
