### ISSUE TITLE
Mod not loading with 1.12.2 on server or client

### ISSUE THREAD

**Issue by ITCMD** [thedarkcolour/Future-MC#186]
Im running a 1.12.2 server and the mods are not loading in the forge server or client.

Client log: [latest.log](https://github.com/thedarkcolour/Future-MC/files/5070645/latest.log)
Server log: [latest.log](https://github.com/thedarkcolour/Future-MC/files/5070657/latest.log)

**Comment by thedarkcolour** [comment]
Logs don't match what you're saying and it's not a future mc problem

**Comment by ITCMD** [comment]
All I know is that I placed the 1.12 mod in the mods folder of my 1.12 server and on my client, and while other mods worked, the future-mc mods added no features. I didnt see any mention on the future-mc mod in logs when searching for it, so I figured it wasnt identified as a mod or something along those lines.
