### ISSUE TITLE
JEI support for machines

### ISSUE THREAD

**Issue by IronPiston** [thedarkcolour/Future-MC#19]
Currently blocks like the composter and blast furnace have no JEI tabs, making it impossible to see what blocks they support.

For the composter tab specifically, maybe it could list all the blocks in one big grid on the left, and have an arrow showing what resulting item they make on the right.

**Comment by thedarkcolour** [comment]
I will attempt to add more mod compatibility in 0.1.7. 
The composter only makes bonemeal, and its default list of items corresponds to the [actual list in 1.14](https://minecraft.gamepedia.com/Composter#Composting). If you need to add or remove items from this list, MineTweaker compatibility is coming in 0.1.6.

**Comment by thedarkcolour** [comment]
I am going to add compatibility for the Campfire in 0.1.12. I have got it to work, I just need to work out a few more bugs and possibly add JEI support for other machines.

**Comment by thedarkcolour** [comment]
Added support for Campfire, Smoker, and Blast Furnace.
