### ISSUE TITLE
Bees and flowers 1.12.2

### ISSUE THREAD

**Issue by Zergmazter** [thedarkcolour/Future-MC#193]
Would it be possible to add an option in the config or crafttweaker compatibility that allowed us to choose if a flower is replaced by another block after a bee is done pollinating it? That is the bare minimum I could think of so that we could build ourselves some mod inter-compatibility via configs/crafttweaker.

**Comment by thedarkcolour** [comment]
No. That's not really how bees work in vanilla, so I'd just recommend you make a separate mod that adds this functionality.
