### ISSUE TITLE
[1.15.2] Smithing Table Recipe Consumes Entire Stack

### ISSUE THREAD

**Issue by coolsimulations** [thedarkcolour/Future-MC#197]
**Version**: FutureMC - 1.15.2 - 1.0.1

**Overview**: I am currently in the process of adding support for FutureMC into my three mods ([SurvivalPlus](https://www.curseforge.com/minecraft/mc-mods/survivalplus), [MoreThanAPickaxe](https://www.curseforge.com/minecraft/mc-mods/more-than-a-pickaxe), and [SurvivalPlus Lightsabers](https://www.curseforge.com/minecraft/mc-mods/survivalplus-lightsabers)) and have found an issue with the Smithing Table. When placing an entire stack into the first input slot of the Smithing Table and crafting a recipe, the Table consumes the entire stack not just one.

**Steps to Reproduce:**
*1.* Create a new recipe JSON that has an input item that can be stackable (not a tool)
*2.* Place a Smithing Table
*3.* Place a Fullstack of 64 items into the first input slot for the recipe.
*4.* Take out the result and notice that the first input stack has been entirely consumed.

**Comment by thedarkcolour** [comment]
Hm I'll look at it
