### ISSUE TITLE
[suggestion] crafttweaker recipe support for new machines

### ISSUE THREAD

**Issue by xkforce** [thedarkcolour/Future-MC#2]
It would be nice for pack makers like myself to have that kind of control over the recipes that these new machines have available to them.

**Comment by thedarkcolour** [comment]
New machines? Are you referring to the Stonecutter?

**Comment by xkforce** [comment]
Indeed.

**Comment by thedarkcolour** [comment]
I plan to add two machines update 0.1.2, the Smelter and the Blast Furnace. These function like the blocks from 1.14 and take recipes from the Furnace.

**Comment by xkforce** [comment]
Neat.  I assume the blast furnace and smelter will use ore dictionaries to determine what can and can't be smelted in them. i.e. in 1.14 smokers are food only and blast furnaces are pretty much everything else

**Comment by thedarkcolour** [comment]
That's right! I am using Ore Dictionary to craft the items.

**Comment by thedarkcolour** [comment]
Compatibility for Composter is coming next update.

**Comment by xkforce** [comment]
Excellent.  Keep up the good work.

**Comment by thedarkcolour** [comment]
I have released 0.1.6 with CraftTweaker support for Composters. [Check the wiki for functions.](https://github.com/thedarkcolour/Future-MC/wiki) Let me know if I should any more functions for the composter.

**Comment by Fireztonez** [comment]
Can you add crafttweaker support for the Blast Furnace and the Smoker please?

Thank's for the new update with the composter crafttweaker support!

**Comment by thedarkcolour** [comment]
0.1.7 has CraftTweaker support for Blast Furnace and Smoker. @Fireztonez

**Comment by thedarkcolour** [comment]
I have redone Blast Furnace and Smoker recipes to include custom inputs and outputs. For example, you could smelt a piece of string into charcoal. I also added the Campfire with CraftTweaker support. I'll add the functions later on the wiki. Most upcoming machines will come with CraftTweaker support.
