### ISSUE TITLE
[1.12.2] No recipe for soul lantern and soul torch

### ISSUE THREAD

**Issue by Sixdd6** [thedarkcolour/Future-MC#200]
Just as the title says, the soul lantern and soul torch have no recipes.

Minecraft Version: 1.12.2
Forge: 2854
Mod Version: 0.2.4.1

**Comment by thedarkcolour** [comment]
intended because there is no soil fire

**Comment by Sixdd6** [comment]
Why the need for the fire? The soul torch is crafted with soul sand, no need for the soil fire. [link to wiki](https://minecraft.fandom.com/wiki/Soul_Torch)

**Comment by thedarkcolour** [comment]
I will look at it
