### ISSUE TITLE
[1.12.2] Future MC installed causes wrong particles of Colorful Slimes

### ISSUE THREAD

**Issue by Vodulm** [thedarkcolour/Future-MC#203]
The slimes from [Colorful Slimes ](https://www.curseforge.com/minecraft/mc-mods/colorful-slimes) mod having wrong particles if Future MC is also installed (vanilla Slime is not affected)
![2020-10-06_01 11 22](https://user-images.githubusercontent.com/73194834/96631395-f37e0100-131e-11eb-907d-e7a8b8983922.png)
![2020-10-09_02 57 57](https://user-images.githubusercontent.com/73194834/96631402-f4af2e00-131e-11eb-9f3f-d52c862ed039.png)

Without Future MC:
![2020-10-09_03 05 09](https://user-images.githubusercontent.com/73194834/96631441-0395e080-131f-11eb-8bfb-68af7afc59c4.png)

**Comment by thedarkcolour** [comment]
I think this is an issue in Colorful Slimes, but I can't tell because the mod is closed source and doesn't seem to be maintained anymore.
