### ISSUE TITLE
[1.15.2] Items not spawning drops

### ISSUE THREAD

**Issue by jasnitig** [thedarkcolour/Future-MC#204]
Hey, I love this mod! It's helped so much in making a more complete modded 1.15.2 experience. However, when playing in the Nether, I noticed none of the added blocks had drops; the new fungi, blackstone, shroomlights, soul soil, nether gold, and basalt, at least. I was really hoping to make some blackstone builds; when do you think this feature will be implemented?

**Comment by thedarkcolour** [comment]
That's the reason I kept it as a preview version. Adding the drops is a hassle and I wanted to get out an update to show the progress that's been made

**Comment by thedarkcolour** [comment]
I am no longer maintaining 1.15.2 because it is a version with a declining playerbase.
