### ISSUE TITLE
[1.12.2] FutureMC Nether World Generator shows up in 'Create World' generator selection list

### ISSUE THREAD

**Issue by BrisingrAerowing** [thedarkcolour/Future-MC#208]
![2020-11-02_15 40 32](https://user-images.githubusercontent.com/250409/97917045-e0593100-1d21-11eb-83fc-311edfa35eac.png)

**Comment by thedarkcolour** [comment]
What version are you using?

**Comment by BrisingrAerowing** [comment]
1.12.2 0.2.4.1
