### ISSUE TITLE
SErver crash on Version 0.1.6b

### ISSUE THREAD

**Issue by Poke5555** [thedarkcolour/Future-MC#21]
Downgrading to 0.1.5c fixes the issue :)
https://pastebin.com/F3DdEMak

**Comment by BinaryCrafter** [comment]
Also seeing this with a custom mod pack I've just put together. Downgraded and it runs fine.

**Comment by thedarkcolour** [comment]
I will release fix soon. I have to get Composter automation working before I can update. Other things might also be waiting.

**Comment by thedarkcolour** [comment]
Fixed in 0.1.7.
