### ISSUE TITLE
[1.12.2] Suggestion

### ISSUE THREAD

**Issue by Taknax** [thedarkcolour/Future-MC#211]
Campfire goes out by rain and compatiblity with tough as nails.

**Comment by thedarkcolour** [comment]
I originally had the rain part but I removed it because it didn't fit vanilla and I'm not sure about Tough as Nails

**Comment by Taknax** [comment]
if the rain part not considered would be fine. TAN would be awesome. It is used by many player. I hope u gonna consider it, if the implemantation is not to hard.
Ty for reply and this awesome mod!

**Comment by democat3457** [comment]
why the close

**Comment by Taknax** [comment]
I thought you dont gonna investigate time. Was jsut cleaning my issues.
