### ISSUE TITLE
[1.12.2] Stripping Logs Causing Game to Freeze

### ISSUE THREAD

**Issue by SaltSouls** [thedarkcolour/Future-MC#216]
If you disabled the stripped variants for logs, but not the right click functionality behind it, it will create a missing texture block. Upon trying to break said block, the game will freeze up. This can be fixed by disabling the stripping mechanic, but will make it impossible to receive the stripped wood blocks as there is no recipe for them outside of right clicking them with an axe in the world.

**Comment by thedarkcolour** [comment]
I guess that's an oversight
