### ISSUE TITLE
[1.12.2] CraftTweaker implementation for the Smoker does not work

### ISSUE THREAD

**Issue by CalaMariGold** [thedarkcolour/Future-MC#217]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/555

**Comment by thedarkcolour** [comment]
I wonder if the blast furnace is also broken?

**Comment by democat3457** [comment]
blast furnace recipes aren't broken, our script for it works in both removing and adding items

**Comment by thedarkcolour** [comment]
I am testing a fix
