### ISSUE TITLE
[1.12.2] Bee Hives cause crash when disabled

### ISSUE THREAD

**Issue by TipsyBeveridge** [thedarkcolour/Future-MC#218]
I disabled the bees part of the mod as well as the other buzzy bees stuff excluding the iron golem config option after discovering that there were too many bee hives and bees in a new world I started. I restarted Minecraft and loaded started a new world to see if the bees were disabled and it crashed. 

Here is a pastebin with the crash log info attached to it: https://pastebin.com/wAJ50HkG

**Comment by EdenOfTheWest** [comment]
Bee spawns are way too high/rapid. causes rapid TPS drops. Other mods cannot control spawns either.

**Comment by thedarkcolour** [comment]
There's literally a config for this but ok

**Comment by thedarkcolour** [comment]
Oh no the bees are crazy

**Comment by thedarkcolour** [comment]
Temporarily removed the bee hives on dynamic trees in 0.2.6 which fixes the issue but I will keep this in mind next time i try to add it

**Comment by thedarkcolour** [comment]
Oops wrong issue
