### ISSUE TITLE
[1.12.2] Bees spawn excessively

### ISSUE THREAD

**Issue by Darkmega18** [thedarkcolour/Future-MC#219]
![image](https://user-images.githubusercontent.com/8104689/106707800-f094eb00-6645-11eb-805f-cbdda7b67c68.png)

these numbers...
https://cdn.discordapp.com/attachments/797335595315494922/806410673755521044/unknown.png
https://cdn.discordapp.com/attachments/797335595315494922/806410997715042354/unknown.png
https://cdn.discordapp.com/attachments/797335595315494922/806411279178399754/unknown.png

they don't seem to line up all that good.

**Comment by thedarkcolour** [comment]
like what?

**Comment by Darkmega18** [comment]
sorry, go again. why the hell did you answer so quickly. I accidentally hit enter. X_x thinking it'd go down a line but it just sent it empty on me.

**Comment by thedarkcolour** [comment]
I have a discord webhook that alerts me

**Comment by thedarkcolour** [comment]
?????

**Comment by democat3457** [comment]
bee spawn rates seem pretty excessive now... they really like those trees, I guess - lol

**Comment by Darkmega18** [comment]
ah, go figure. but anyways, shown in the config picture vs the 3 pictures ingame of a new world I just made while testing some other stuff and noticed it. the bee spawn rates seem to be spawning absolute maximum. I'm not sure if this was an issue with the last version as I was always just on a void test platform doing crafttweaker and testing related stuff. but I made a world just randomly just now while working and it exploded.

**Comment by thedarkcolour** [comment]
I think I figured it out

**Comment by Darkmega18** [comment]
looking around, the bees in the adjacent savanna seem fine. theres like no bees there.

**Comment by thedarkcolour** [comment]
They don't spawn in that biome

**Comment by Darkmega18** [comment]
ah well. whoops. thought they just end up on trees rarely. but yeah, I just realized that myself when I even had the config up just next to me. >_>

**Comment by thedarkcolour** [comment]
Why am I not getting this bug on my end?

**Comment by Darkmega18** [comment]
ah crap. don't tell me it's a terrible-terrible mod conflict related bug again... in a 216 (forge reported) strong pack. :V

**Comment by thedarkcolour** [comment]
[Maybe try this jar?](https://www.mediafire.com/file/3i2k9jaxurey1de/future-mc-1.12.2-0.2.6pre.jar/file)

**Comment by Darkmega18** [comment]
alrighty. I'll try regenerating the same world and see what happens, right?

**Comment by Darkmega18** [comment]
not a single bee now. must be pretty rare normally. o.o

**Comment by thedarkcolour** [comment]
So you think the issue is resolved?

**Comment by Darkmega18** [comment]
I'll turn the forest bees up temporarily and gen a third to see if they spawn at all atleast. otherwise yes.

**Comment by Darkmega18** [comment]
ok nope. at 0.3 it has gone from bees forever, to bees never. :V

**Comment by thedarkcolour** [comment]
What biome are they spawning in?

**Comment by Darkmega18** [comment]
not the forest as far as I could tell when I was testing it, which was also where the overspawn was when it initially occurred.

**Comment by thedarkcolour** [comment]
Temporarily removed the bee hives on dynamic trees in 0.2.6 which fixes the issue but I will keep this in mind next time i try to add it

**Comment by Darkmega18** [comment]
well alrighty then... they're technically fluff in my modpack cause of rustic and pams bees and crafttweaking which're easier to deal with, but they are nice to see floating around, but I guess not anymore.
