### ISSUE TITLE
Trident Problems

### ISSUE THREAD

**Issue by Boolyman** [thedarkcolour/Future-MC#22]
The Trident was pretty much what caught my eye about your mod since my upcoming pack is water based.  Unfortunately the Trident doesn't function properly underwater.  The vanilla Trident keeps its underwater velocity when thrown... thats what makes it better than a bow underwater. Your Trident travels like 3 blocks and then drops strait to the ocean floor.  Is there any way you can make it have its normal thrown velocity underwater?  Also, any chance you could make the damage value configurable?  The thrown damage is super weak.  Thanks for considering.

**Comment by thedarkcolour** [comment]
I'll add a config option that lets you increase the base damage value. An extra attack damage amount. I'll try again with the water drag.

**Comment by thedarkcolour** [comment]
The arrow class forces the trident to go downwards and I haven't created a working projectile class. The damage value is also kept constant in the arrow class, so I wasn't able to do that either. Sorry for the inconvenience.

**Comment by Boolyman** [comment]
Ah, thats dissappointing.  Thanks for trying though.

There are bow mods that add arrows that fly normally underwater.... may want to check to see how they pull that off.

**Comment by thedarkcolour** [comment]
I have found a solution. Fix coming next update.

**Comment by thedarkcolour** [comment]
Fixed in 0.1.11
