### ISSUE TITLE
[1.12.2] Too Many Bees

### ISSUE THREAD

**Issue by LenKagamine** [thedarkcolour/Future-MC#220]
When entering any biome with trees from the 'Traverse' mod, it seems that the game starts to generate an enormous amount of bee nests, to the point where nearly every tree has a nest, each spawning several mobs. Of course, this makes the game almost unplayable. I do not know if this affects other biome mods too, but Biomes O Plenty is unaffected. This affects the 0.2.6 version for 1.12.2, but isn't a problem in the 0.2.4 version of the mod.
![2021-02-05_16 47 06](https://user-images.githubusercontent.com/78622624/107094460-0684e600-67d5-11eb-9a35-8132bbc2ae8e.png)

**Comment by thedarkcolour** [comment]
AAAAAAAAAAAAAAAAAAAAAAAA

**Comment by LenKagamine** [comment]
Sorry, I didn't know how to add labels.

**Comment by thedarkcolour** [comment]
You can't add labels I'm just annoyed at the bug

**Comment by thedarkcolour** [comment]
Fixed in 0.2.6.1
