### ISSUE TITLE
[1.12.2]Bee pollination zenscript doesn't work anymore?

### ISSUE THREAD

**Issue by Terra-B-Welch** [thedarkcolour/Future-MC#221]
So I updated to version 0.2.6.1 of Future MC and after updated my crafttweaker scripts to the new format I've found all but the bee pollination work.

My script for bees.
https://pastebin.com/qYjEDP90

Error that occurs,
https://pastebin.com/FtqpWx8Y

I don't understand how it could be wrong on my end, I followed the wiki and see no mistakes.

**Comment by democat3457** [comment]
you want to use a BlockState - https://docs.blamejared.com/1.12/en/Vanilla/Brackets/Bracket_BlockState/

**Comment by thedarkcolour** [comment]
^ Yep it's IBlockState

**Comment by Terra-B-Welch** [comment]
the script is using "import crafttweaker.block.IBlockState;" where are you people seeing IItemStack in my script?

**Comment by thedarkcolour** [comment]
In the log

**Comment by Terra-B-Welch** [comment]
But why would it even look for that if I'm importing IBlockState?

In the case for the flowers I'm trying to use, theres no real difference between block and item ID.
I guess I wasted my time bringing this up then huh? Thanks for nothing I guess. :s

**Comment by thedarkcolour** [comment]
<blockstate:minecraft:flower>

**Comment by democat3457** [comment]
your brackets are wrong - `<blockstate:minecraft:dirt>` versus `<minecraft:dirt>`. the former returns an `IBlockState`, whereas the latter is an `IItemStack`.
