### ISSUE TITLE
1.12.2 Bee nest overspawning

### ISSUE THREAD

**Issue by urnagemiaohnoh** [thedarkcolour/Future-MC#222]
Bee nests are spawning in every block of dynamic oak wood, so bees are all over the world

![IMG_20210223_115936_515~2](https://user-images.githubusercontent.com/49655936/108862339-e6279a80-75ce-11eb-83fa-ab416956676a.jpg)

**Comment by democat3457** [comment]
the latest version should have fixed this

**Comment by thedarkcolour** [comment]
Fixed in 0.2.6.1
