### ISSUE TITLE
Crash when putting specific items into grindstone

### ISSUE THREAD

**Issue by futurenp** [thedarkcolour/Future-MC#23]
Crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3 (1).jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  Quark Plugin (Quark-r1.5-164.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  BCModPlugin (backpacks+1.12.2+-+3.5.6.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 7/8/19 10:08 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.herobrine.future.tile.grindstone.ContainerGrindstone.handleCrafting(ContainerGrindstone.java:172)
	at com.herobrine.future.tile.grindstone.ContainerGrindstone$1.onContentsChanged(ContainerGrindstone.java:36)
	at net.minecraftforge.items.ItemStackHandler.setStackInSlot(ItemStackHandler.java:60)
	at net.minecraftforge.items.SlotItemHandler.func_75215_d(SlotItemHandler.java:80)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.herobrine.future.tile.grindstone.ContainerGrindstone.handleCrafting(ContainerGrindstone.java:172)
	at com.herobrine.future.tile.grindstone.ContainerGrindstone$1.onContentsChanged(ContainerGrindstone.java:36)
	at net.minecraftforge.items.ItemStackHandler.setStackInSlot(ItemStackHandler.java:60)
	at net.minecraftforge.items.SlotItemHandler.func_75215_d(SlotItemHandler.java:80)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.herobrine.future.tile.grindstone.GuiGrindstone

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Naterbobber'/834763, l='MpServer', x=1484.98, y=21.50, z=894.97]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-40,64,256), Chunk: (at 8,4,0 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 19961554 game time, 8101586 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 110 total; [EntityPlayerSP['Naterbobber'/834763, l='MpServer', x=1484.98, y=21.50, z=894.97], EntityLatchedRenderer['unknown'/1, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/2, l='MpServer', x=8.50, y=65.00, z=8.50], EntitySkeleton['Skeleton'/870407, l='MpServer', x=1499.50, y=56.00, z=915.50], EntityHat['unknown'/7691, l='MpServer', x=1420.50, y=29.00, z=903.50], EntityZombie['Zombie'/870950, l='MpServer', x=1408.50, y=65.00, z=879.50], EntityWolf['Wolf'/861241, l='MpServer', x=1520.50, y=77.59, z=907.30], EntityWolf['Wolf'/861240, l='MpServer', x=1521.45, y=83.00, z=925.27], EntityArchaeologist['Archaeologist'/861243, l='MpServer', x=1521.00, y=28.00, z=966.00], EntityTroll['Troll'/870458, l='MpServer', x=1431.50, y=32.00, z=935.50], EntityWolf['Wolf'/861242, l='MpServer', x=1522.54, y=77.58, z=907.82], EntityFishCod['Cod'/869428, l='MpServer', x=1412.39, y=61.00, z=854.79], EntityMinecartChest['Minecart with Chest'/861238, l='MpServer', x=1535.50, y=14.06, z=821.50], EntityFishCod['Cod'/869427, l='MpServer', x=1411.50, y=62.00, z=859.50], EntitySkeleton['Skeleton'/870990, l='MpServer', x=1482.91, y=17.99, z=901.70], EntityCreeper['Creeper'/869962, l='MpServer', x=1437.50, y=30.00, z=911.50], EntityZombie['Zombie'/869956, l='MpServer', x=1420.50, y=29.00, z=903.50], EntityFishPufferfish['Pufferfish'/871004, l='MpServer', x=1463.61, y=59.20, z=914.31], EntityFishPufferfish['Pufferfish'/871001, l='MpServer', x=1467.58, y=56.20, z=917.28], EntityFishCod['Cod'/871000, l='MpServer', x=1506.50, y=59.00, z=837.50], EntityFishPufferfish['Pufferfish'/871003, l='MpServer', x=1464.77, y=58.00, z=910.49], EntityFishPufferfish['Pufferfish'/871002, l='MpServer', x=1466.37, y=60.20, z=916.31], EntityCreeper['Creeper'/870485, l='MpServer', x=1554.50, y=38.00, z=875.50], EntityFishCod['Cod'/870997, l='MpServer', x=1508.50, y=59.00, z=840.50], EntityFishCod['Cod'/870999, l='MpServer', x=1507.50, y=59.00, z=835.50], EntityCreeper['Creeper'/870486, l='MpServer', x=1555.50, y=38.00, z=875.50], EntityFishCod['Cod'/870998, l='MpServer', x=1508.50, y=59.00, z=836.50], EntitySkeleton['Skeleton'/870992, l='MpServer', x=1482.30, y=17.34, z=899.38], EntitySkeleton['Skeleton'/870995, l='MpServer', x=1482.30, y=17.36, z=901.30], EntityBat['Bat'/870505, l='MpServer', x=1498.54, y=29.03, z=961.05], EntityHat['unknown'/7781, l='MpServer', x=1514.13, y=57.72, z=869.15], EntityCreeper['Creeper'/870496, l='MpServer', x=1421.50, y=46.00, z=874.50], EntityHat['unknown'/7792, l='MpServer', x=1472.48, y=16.00, z=852.80], EntityItemFrame['Item Frame'/835197, l='MpServer', x=1338.50, y=70.50, z=783.03], EntityFishPufferfish['Pufferfish'/871033, l='MpServer', x=1487.30, y=61.20, z=859.50], EntityFishPufferfish['Pufferfish'/871032, l='MpServer', x=1481.37, y=56.88, z=860.26], EntityFishPufferfish['Pufferfish'/871034, l='MpServer', x=1478.23, y=59.00, z=856.55], EntityFishCod['Cod'/871029, l='MpServer', x=1547.66, y=61.00, z=891.39], EntityFishCod['Cod'/871028, l='MpServer', x=1550.50, y=61.00, z=892.50], EntityFishPufferfish['Pufferfish'/871031, l='MpServer', x=1475.69, y=61.20, z=862.36], EntityFishCod['Cod'/871030, l='MpServer', x=1550.49, y=61.03, z=890.51], EntityFishCod['Cod'/871027, l='MpServer', x=1551.50, y=61.00, z=887.50], EntityFishCod['Cod'/871065, l='MpServer', x=1483.50, y=59.63, z=827.15], EntityFishCod['Cod'/871064, l='MpServer', x=1486.50, y=59.00, z=823.50], EntityHat['unknown'/7833, l='MpServer', x=1541.70, y=82.06, z=927.50], EntityFishCod['Cod'/871063, l='MpServer', x=1485.50, y=59.00, z=822.51], EntityFishCod['Cod'/871062, l='MpServer', x=1484.50, y=59.00, z=820.50], EntityHat['unknown'/157, l='MpServer', x=1484.98, y=21.50, z=894.97], EntityHat['unknown'/7838, l='MpServer', x=1435.25, y=32.08, z=943.40], EntityZombie['Zombie'/871080, l='MpServer', x=1470.50, y=16.00, z=843.50], EntityCreeper['Creeper'/871083, l='MpServer', x=1470.50, y=16.00, z=849.17], EntityCreeper['Creeper'/871102, l='MpServer', x=1506.50, y=9.00, z=838.50], EntityBat['Bat'/870587, l='MpServer', x=1514.13, y=57.72, z=869.15], EntityBat['Bat'/870581, l='MpServer', x=1464.65, y=60.10, z=939.17], EntityHat['unknown'/7864, l='MpServer', x=1503.43, y=57.81, z=865.70], EntityItemFrame['Item Frame'/835248, l='MpServer', x=1335.03, y=71.50, z=785.50], EntityHat['unknown'/7869, l='MpServer', x=1482.91, y=17.99, z=901.70], EntitySkeleton['Skeleton'/871088, l='MpServer', x=1415.50, y=63.00, z=887.50], EntityHat['unknown'/7870, l='MpServer', x=1482.30, y=17.36, z=901.30], EntityBat['Bat'/871119, l='MpServer', x=1421.75, y=26.04, z=868.25], EntityWolf['Wolf'/861383, l='MpServer', x=1541.70, y=82.06, z=927.50], EntityBat['Bat'/870081, l='MpServer', x=1416.81, y=30.06, z=900.96], EntityStoneling['Stoneling'/871105, l='MpServer', x=1507.50, y=9.00, z=839.50], EntityZombie['Zombie'/871106, l='MpServer', x=1512.48, y=9.00, z=842.30], EntityCreeper['Creeper'/870633, l='MpServer', x=1439.50, y=30.00, z=907.50], EntityCreeper['Creeper'/870632, l='MpServer', x=1442.50, y=30.00, z=905.50], EntityTroll['Troll'/870641, l='MpServer', x=1535.50, y=34.00, z=940.50], EntityFishCod['Cod'/870666, l='MpServer', x=1481.50, y=62.00, z=819.50], EntityDweller['Dweller'/870685, l='MpServer', x=1472.48, y=16.00, z=852.80], EntityWolf['Wolf'/835357, l='MpServer', x=1432.70, y=62.33, z=949.50], EntityDweller['Dweller'/870684, l='MpServer', x=1471.91, y=15.00, z=862.56], EntitySheep['Sheep'/835358, l='MpServer', x=1407.49, y=70.00, z=928.71], EntityStoneling['Stoneling'/870693, l='MpServer', x=1426.50, y=21.00, z=898.50], EntitySkeleton['Skeleton'/869709, l='MpServer', x=1418.50, y=26.00, z=870.50], EntitySkeleton['Skeleton'/870733, l='MpServer', x=1480.70, y=8.00, z=833.73], EntitySkeleton['Skeleton'/870732, l='MpServer', x=1478.50, y=8.00, z=831.50], EntityZombie['Zombie'/869711, l='MpServer', x=1416.50, y=26.00, z=876.50], EntityZombie['Zombie'/870735, l='MpServer', x=1478.50, y=8.00, z=830.50], EntityZombie['Zombie'/869710, l='MpServer', x=1418.50, y=26.00, z=868.50], EntityZombie['Zombie'/870734, l='MpServer', x=1480.70, y=8.00, z=832.92], EntityCreeper['Creeper'/870736, l='MpServer', x=1499.50, y=56.00, z=965.50], EntityFishCod['Cod'/870777, l='MpServer', x=1557.16, y=62.00, z=881.23], EntityFishCod['Cod'/870776, l='MpServer', x=1556.50, y=62.00, z=878.50], EntityFishCod['Cod'/870779, l='MpServer', x=1552.50, y=62.00, z=879.50], EntityFishCod['Cod'/870778, l='MpServer', x=1558.38, y=60.05, z=878.86], EntityBat['Bat'/870797, l='MpServer', x=1435.25, y=32.08, z=943.40], EntityEnderman['Enderman'/870299, l='MpServer', x=1472.50, y=16.00, z=851.50], EntityBat['Bat'/870801, l='MpServer', x=1436.95, y=28.19, z=964.04], EntityBat['Bat'/870803, l='MpServer', x=1435.10, y=30.00, z=951.14], EntitySkeleton['Skeleton'/870313, l='MpServer', x=1475.31, y=34.00, z=906.49], EntityWolf['Wolf'/861096, l='MpServer', x=1512.81, y=62.54, z=872.75], EntityMinecartChest['Minecart with Chest'/861093, l='MpServer', x=1514.50, y=9.06, z=847.50], EntityArchaeologist['Archaeologist'/861094, l='MpServer', x=1517.00, y=20.00, z=838.00], EntityFishPufferfish['Pufferfish'/870837, l='MpServer', x=1506.50, y=61.00, z=829.50], EntityFishPufferfish['Pufferfish'/870836, l='MpServer', x=1508.50, y=61.00, z=827.50], EntityFishPufferfish['Pufferfish'/870839, l='MpServer', x=1502.50, y=61.00, z=829.50], EntityFishPufferfish['Pufferfish'/870838, l='MpServer', x=1502.50, y=61.00, z=827.50], EntityFishCod['Cod'/870833, l='MpServer', x=1502.50, y=52.00, z=838.50], EntityFishCod['Cod'/870832, l='MpServer', x=1500.50, y=52.00, z=837.50], EntityFishCod['Cod'/870834, l='MpServer', x=1501.50, y=52.00, z=837.50], EntityZombie['Zombie'/870344, l='MpServer', x=1495.76, y=50.00, z=931.27], EntityFishCod['Cod'/867821, l='MpServer', x=1409.25, y=62.20, z=850.63], EntitySquid['Squid'/870895, l='MpServer', x=1503.43, y=57.81, z=865.70], EntitySquid['Squid'/870894, l='MpServer', x=1504.60, y=59.24, z=863.51], EntityFishCod['Cod'/870397, l='MpServer', x=1482.50, y=56.00, z=821.50], EntityFishCod['Cod'/870396, l='MpServer', x=1482.50, y=55.98, z=820.50], EntityFishCod['Cod'/870395, l='MpServer', x=1480.16, y=55.15, z=823.84], EntityFishCod['Cod'/870394, l='MpServer', x=1479.50, y=56.00, z=824.50], EntitySquid['Squid'/870897, l='MpServer', x=1511.25, y=58.83, z=872.40], EntitySquid['Squid'/870896, l='MpServer', x=1509.55, y=57.88, z=872.60]]
	Retry entities: 2 total; [EntityLatchedRenderer['unknown'/1, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/2, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 752600144 bytes (717 MB) / 2526543872 bytes (2409 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                     | Source                                        | Signature                                |
	|:------ |:--------------------- |:--------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                      | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                   | 9.42                        | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                   | forge-1.12.2-14.23.5.2838-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2838                | forge-1.12.2-14.23.5.2838-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | tnt_utilities_core    | 1.2.3                       | minecraft.jar                                 | None                                     |
	| LCHIJA | dsurroundcore         | 3.5.4.3                     | minecraft.jar                                 | None                                     |
	| LCHIJA | ambience              | GRADLE:VERSION-GRADLE:BUILD | Ambience+1.1-10 (1).jar                       | None                                     |
	| LCHIJA | antiqueatlas          | 4.5.1                       | antiqueatlas-1.12.2-4.5.1.jar                 | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | antiqueatlasoverlay   | 1.2                         | antiqueatlas-1.12.2-4.5.1.jar                 | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | applecore             | 3.2.0                       | AppleCore-mc1.12.2-3.2.0.jar                  | None                                     |
	| LCHIJA | crafttweaker          | 4.1.19                      | CraftTweaker2-1.12-4.1.19.jar                 | None                                     |
	| LCHIJA | mtlib                 | 3.0.6                       | MTLib-3.0.6.jar                               | None                                     |
	| LCHIJA | modtweaker            | 4.0.17                      | modtweaker-4.0.17.jar                         | None                                     |
	| LCHIJA | jei                   | 4.15.0.283                  | jei_1.12.2-4.15.0.283.jar                     | None                                     |
	| LCHIJA | quark                 | r1.5-164                    | Quark-r1.5-164.jar                            | None                                     |
	| LCHIJA | autoreglib            | 1.3-30                      | AutoRegLib-1.3-30.jar                         | None                                     |
	| LCHIJA | backpacks16840        | 3.5.6                       | backpacks+1.12.2+-+3.5.6.jar                  | None                                     |
	| LCHIJA | baubles               | 1.5.2                       | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2439                  | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar | None                                     |
	| LCHIJA | ctm                   | MC1.12.2-0.3.3.22           | CTM-MC1.12.2-0.3.3.22.jar                     | None                                     |
	| LCHIJA | chisel                | MC1.12.2-0.2.1.34           | Chisel-MC1.12.2-0.2.1.34.jar                  | None                                     |
	| LCHIJA | clumps                | 3.1.2                       | Clumps-3.1.2.jar                              | None                                     |
	| LCHIJA | colytra               | 1.2.0                       | colytra-1.12.2-1.2.0.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | morpheus              | 1.12.2-3.5.106              | Morpheus-1.12.2-3.5.106.jar                   | None                                     |
	| LCHIJA | comforts              | 1.4.1.2                     | comforts-1.12.2-1.4.1.2.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | conduit               | 1.0.2                       | conduit-1.0.2.jar                             | None                                     |
	| LCHIJA | coralreef             | 2.0                         | CoralReef-2.5-1.12.2.jar                      | None                                     |
	| LCHIJA | cosmeticarmorreworked | 1.12.2-v4a                  | CosmeticArmorReworked-1.12.2-v4a (1).jar      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | craftingautomat       | 1.0.5                       | CraftingAutomat-MC1.12.2-1.0.5.jar            | None                                     |
	| LCHIJA | ctgui                 | 1.0.0                       | CraftTweaker2-1.12-4.1.19.jar                 | None                                     |
	| LCHIJA | crafttweakerjei       | 2.0.3                       | CraftTweaker2-1.12-4.1.19.jar                 | None                                     |
	| LCHIJA | custommainmenu        | 2.0.9                       | CustomMainMenu-MC1.12.2-2.0.9 (1).jar         | None                                     |
	| LCHIJA | csb_ench_table        | 1.1.3                       | EnchantingTable-1.12-1.1.3.jar                | None                                     |
	| LCHIJA | fastleafdecay         | v14                         | FastLeafDecay-v14 (1).jar                     | None                                     |
	| LCHIJA | fivefeetsmall         | 1.0                         | FiveFeetSmall-v1.0-1.12.2.jar                 | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCHIJA | foodexpansion         | 1.3                         | FoodExpansion1.3.3-1.12.2.jar                 | None                                     |
	| LCHIJA | minecraftfuture       | 0.1.7                       | future-mc-0.1.7.jar                           | None                                     |
	| LCHIJA | gravestone            | 1.10.2                      | gravestone-1.10.2.jar                         | None                                     |
	| LCHIJA | ichunutil             | 7.2.1                       | iChunUtil-1.12.2-7.2.1.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | hats                  | 7.0.0                       | Hats-1.12.2-7.0.2.jar                         | None                                     |
	| LCHIJA | hopperducts           | 1.5                         | hopperducts-mc1.12-1.5.jar                    | None                                     |
	| LCHIJA | waila                 | 1.8.26                      | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | llibrary              | 1.7.19                      | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire            | 1.7.0                       | iceandfire-1.7.0-1.12.2.jar                   | None                                     |
	| LCHIJA | inventorytweaks       | 1.64+dev.146.2180b27        | InventoryTweaks-1.64+dev.146.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jaff                  | 1.7_for_1.12                | JustAFewFish-1.7_for_1.12 (1).jar             | None                                     |
	| LCHIJA | materialchanger       | 1.0                         | materialchanger1.0.3-1.12.2.jar               | None                                     |
	| LCHIJA | mtrm                  | 1.2.2.30                    | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar    | None                                     |
	| LCHIJA | mowziesmobs           | 1.5.4                       | mowziesmobs-1.5.4.jar                         | None                                     |
	| LCHIJA | mumboredstone         | 0.3.3                       | mumboredstone-0.3.3.jar                       | None                                     |
	| LCHIJA | pitweaks              | 1.12-1.1.1                  | PiTweaks-1.12-1.1.1.jar                       | None                                     |
	| LCHIJA | railsplus             | 1.1.1                       | railsplus-1.1.1.jar                           | None                                     |
	| LCHIJA | randomenchantments    | @VERSION@                   | randomenchants-0.1.2.jar                      | None                                     |
	| LCHIJA | sandro                | 1.2d                        | Redstone+++ver1.2d.jar                        | None                                     |
	| LCHIJA | redstoneplusplus      | 1.2d                        | Redstone+++ver1.2d.jar                        | None                                     |
	| LCHIJA | resourceloader        | 1.5.3                       | ResourceLoader-MC1.12.1-1.5.3 (1).jar         | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | shulkerbox            | 1.3.0                       | shulkerbox-1.3.0.jar                          | None                                     |
	| LCHIJA | simplecorn            | 2.5.10                      | SimpleCorn1.12-1.12-2.5.10.jar                | None                                     |
	| LCHIJA | snad                  | 1.12.1-1.7.09.16a           | Snad-1.12.1-1.7.09.16a.jar                    | None                                     |
	| LCHIJA | tnt_utilities         | 1.2.3                       | tnt_utilities-mc1.12-1.2.3.jar                | None                                     |
	| LCHIJA | torohealthmod         | 1.12.2-11                   | torohealth-1.12.2-11.jar                      | None                                     |
	| LCHIJA | ts2k16                | 1.2.10                      | Twerk-Sim-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | veining               | 1.3.2                       | veining-1.3.2-1.12.x.jar                      | None                                     |
	| LCHIJA | imvoice               | 0.7.0                       | VoiceChat-1.12.2-0.7.0 (1).jar                | None                                     |
	| LCHIJA | worleycaves           | 1.4.1                       | worleycaves-1.4.1.jar                         | None                                     |
	| LCHIJA | orelib                | 3.5.2.2                     | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround             | 3.5.4.3                     | DynamicSurroundings-1.12.2-3.5.4.3.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | vt                    | 1.12.2-1.5.2                | VanillaTweaks-1.12.2-1.5.2.jar                | None                                     |
	| LCHIJA | hungeroverhaul        | 1.12.2-1.3.3.jenkins148     | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar    | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3 (1).jar)
  lumien.resourceloader.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
Quark Plugin (Quark-r1.5-164.jar)
  vazkii.quark.base.asm.ClassTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.2.0.jar)
  c4.colytra.asm.ElytraTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  ljfa.tntutils.asm.ExplosionTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
BCModPlugin (backpacks+1.12.2+-+3.5.6.jar)
  brad16840.core.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.67' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 1-14-textures-for-1-12-2-1559749651.zip, AntiqueAtlasExtra-v1.2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 419.67
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by thedarkcolour** [comment]
What items did you put in? It crashes when checking if a certain enchantment is a curse or not.

**Comment by futurenp** [comment]
I put a diamond helmet with protection 4 in it

**Comment by thedarkcolour** [comment]
Fixed in 0.1.8
