### ISSUE TITLE
After using Lantern, I could not connect the internet

### ISSUE THREAD

**Issue by inputanickname** [thedarkcolour/Future-MC#230]
Hello All,

I am a not a developer or engineer, I am just a ordinary person who downloaded lantern from GITHUB and have issues. I think mybe I can find solutions here, so I put my issue here, If I put in a wrong place, kindly let me know. Thanks.

I installed lantern in a new laptop and using it to sync something yesterday. After I close lantern, I found that my laptop could not reach network, the wifi (let me call it wifii A) I connected shows connected but no internet, and could not open webpages. 
My laptop could reach internet successfully using other wifi, and other device could use this wifi successfully. Just this laptop could not access to internet using this wifi A, I suppose it is because I used lantern before.

I checked its network setting, and used all the methods I could search in the internet. But network still have problems.

I used below methods:
1. change IE conntions setting: 
"Internet protocl version 4" and set "obtain an IP address automatically", "obtain DNS server address automatically"

2. change setting in windows proxy:
turnoff "automaticallydetect setting", 
turnoff "use setupscript"
turnoff "use  a proxy server"

3. cmd - netsh winsock reset

4. cmd - Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

5. delete connections in regedit - HKEY_CURRENT_USERS\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections

6. forget this wifi and re-connect it

7.  uninstall network adapter and reinstall it in device manager

8.  uninstall lantern

9.  Reboot laptop

Now my laptop can reach network, but it takes a long time to open one webpage, some web even could not open.
I was wondering if any one could offer me some other methods to solve my network problem?
Thank you very much!

**Comment by thedarkcolour** [comment]
Uhhh are you lost?

**Comment by democat3457** [comment]
:what:

**Comment by democat3457** [comment]
I'm preetty sure this isn't the Lantern you're looking for.

**Comment by inputanickname** [comment]
> I'm preetty sure this isn't the Lantern you're looking for.

Hello the lantern I downloaded is from https://github.com/getlantern/download

**Comment by thedarkcolour** [comment]
This is completely different... and by the looks of that repo doesn't look like you'll get any support from the devs either
