### ISSUE TITLE
[1.12.2] Bells Cause Crash

### ISSUE THREAD

**Issue by LenKagamine** [thedarkcolour/Future-MC#233]
I only recently noticed this, but when placing a bell, my game would crash. Since I'm playing a lot of mods it might be some sort of compatibility issue. I don't believe it's Optifine, since I've placed bells with that just fine.

Crash Report-
[crash-2021-04-16_21.51.38-client.txt](https://github.com/thedarkcolour/Future-MC/files/6328481/crash-2021-04-16_21.51.38-client.txt)

**Comment by thedarkcolour** [comment]
What exactly are you doing to trigger this?

**Comment by democat3457** [comment]
seems like there's something running a command upon placing the bell - could be an external mod or script?

**Comment by LenKagamine** [comment]
Yeah I just literally placed it and it crashed. I'm not too well-versed in crash reports or anything so I don't know if it's caused by another mod or what.

**Comment by thedarkcolour** [comment]
Could you send the whole debug log?

**Comment by LenKagamine** [comment]
Where would I find that?

**Comment by democat3457** [comment]
`logs/debug.log`

**Comment by thedarkcolour** [comment]
Just gonna close this if there's no logs

**Comment by LenKagamine** [comment]
Well, I found the logs from the day it happened. 
[2021-04-16-2.log](https://github.com/thedarkcolour/Future-MC/files/6681520/2021-04-16-2.log)
[2021-04-16-3.log](https://github.com/thedarkcolour/Future-MC/files/6681521/2021-04-16-3.log)
[2021-04-16-1.log](https://github.com/thedarkcolour/Future-MC/files/6681522/2021-04-16-1.log)

Took me long enough to find them lol. In any case I redownloaded the set of mods I was using and the problem seems to have fixed itself?

**Comment by thedarkcolour** [comment]
Weird. I'll just close it then
