### ISSUE TITLE
[1.12.2] OTG Biome Bundle O Plenty compatible?

### ISSUE THREAD

**Issue by Macleykun** [thedarkcolour/Future-MC#234]
I've been testing for a few hours if FMC works with OTG/Open Terrain Generator. I have this test going on:
Seed: -4562547876164380000
![image](https://user-images.githubusercontent.com/26381427/116787465-6de4c600-aaa4-11eb-9b9c-fd5d383ef9f9.png)
```
        S:"Bee Nest Biome Spawns" <
            biomesoplenty:eucalyptus_forest:100.00
```
I've noticed the mod works well in Biomes O Plenty, but not yet in OTG.

I would like to know if there are some limits where bees can spawn (like that forest). And if it's possible to just select all biomes in one easy way (like saying: *:*:50.00) or (*:*forest*:50.00). That way, it's a bit easier to configure that bees need to spawn more to get a decent chance to find the cute fella's.

 Looking forward to your reply :)

**Comment by Macleykun** [comment]
Tested futher, i can confirm that FMC bees doesn't work with OTG Biome Bundle O Plenty.
I used tellme to gather all the biomes, and added :1000 to each biome under bees.

Biomes o plenty spawns bees everywhere (like expected, good!)
But Biome bundle O Plenty has none, after looking for minutes.

**Comment by thedarkcolour** [comment]
Biome Bundle uses custom structures that FutureMC doesn't patch

**Comment by Macleykun** [comment]
True, however I expected that the biomes that are from Minecraft/biomes o plenty to still show bees.

hence I tried eucalyptus and the cherry blossom

I do thank you for replying to this issue so fast!

**Comment by Macleykun** [comment]
Hey @thedarkcolour i was wondering if we were allowed to submit a fix for the above, ofcours it will only be merged if your requested changes are incorporated.

Hope this is possible, wanted to ask because i saw pulls were mostly accepted here, but license states otherwise.

**Comment by thedarkcolour** [comment]
I'll accept it :D

**Comment by Macleykun** [comment]
Sorry for the lack of updates. Haven't heard from the person in 5 days, have paid for the work but hope to hear something tommorow next week hopefully

**Comment by Macleykun** [comment]
Hey @mooofins how’s it going with the bees and trees :-)?

**Comment by mooofins** [comment]
What I found is a.) there is dynamic trees support, but it's commented out and b.) bees do appear on oak/birch trees, as per vanilla. Ultimately unclear what you're seeing, and I don't have time to look into this, sorry.

Also for others: I am not the same person Macleykun paid, just a random volunteer :).

**Comment by Macleykun** [comment]
Understandable :) thanks for looking into it a bit tho!

**Comment by Macleykun** [comment]
Closing issue, follow: https://github.com/thedarkcolour/Future-MC/issues/86 for progress :)
