### ISSUE TITLE
[1.12.2] problem with my texture pack

### ISSUE THREAD

**Issue by javi12we** [thedarkcolour/Future-MC#238]
hi, i don't know if i'm in the right place and i'm not very expert in these themes of texture packs and mods, but i love this mod and when i use it with my favorite texture pack i get an error in the texture of the trap doors As you can see in the image the corners of the trap door disappear when I use the John Smith Legacy 1.12.2 v13 texture pack, I would appreciate your indications of how I could solve this myself or if it is a problem on the part of the mod, in any case thanks.

sorry for my english
https://imgur.com/a/7KMVLuO

**Comment by thedarkcolour** [comment]
The maker of the texture pack is responsible for fixing this texture issue, I cannot fix it from my side
