### ISSUE TITLE
pandas can't actually attack you and cause a server-side crash if you hit them while they try

### ISSUE THREAD

**Issue by lag42** [thedarkcolour/Future-MC#24]
if you make pandas mad they walk up to you and make noises like they're attacking you but don't actually hit you

if you hit them while they're doing that they cause [this](https://gist.github.com/lag42/0e60723aeaae3b5fa7326d91b0ddd878) server-side crash

**Comment by thedarkcolour** [comment]
Fixed in 0.1.8
