### ISSUE TITLE
[1.12.2] Berry Bush Debug Death Message

### ISSUE THREAD

**Issue by Handeril** [thedarkcolour/Future-MC#240]
Small bug here, nothing too serious.

Dying to a berry bush yields the death message "death.attack.berryBush", it doesn't cause a crash or anything serious, it's just looks like a fallback/default death message.

If this can be fixed sometime in the near future [alongside other fixes], I'd look forward to it.

Thank you for your time.

**Comment by Handeril** [comment]
Thank you!

**Comment by democat3457** [comment]
:D np
