### ISSUE TITLE
[1.12.2] Composter auto-composting and support for adding items

### ISSUE THREAD

**Issue by SanjivanM** [thedarkcolour/Future-MC#242]
Request for auto composting (hopper input/ output items), as well as the ability to specify what items have a 100/85/50% of raising the compost level.

**Comment by thedarkcolour** [comment]
All of these things are already in the mod??

**Comment by thedarkcolour** [comment]
Use CraftTweaker for adding item growth chances

**Comment by SanjivanM** [comment]
is automatic composting in the mod?

**Comment by thedarkcolour** [comment]
Yes
