### ISSUE TITLE
[1.12.2] Problems Building & Running

### ISSUE THREAD

**Issue by Su5eD** [thedarkcolour/Future-MC#249]
### Building
The class `TrapdoorRecipeTest` fails to build because the `junit` dependency has been removed in the latest commit.

### Running
ForgeGradle 3+ versions are known to cause multiple runtime issues on 1.12.2:
- Mod resources not loading
- Dependency coremods & ATs not loading
- Crashing CodeChickenLib
- ASM throwing a (caught) IllegalArgumentException

The first error to show up when running the mod is CCL, which crashes with the following error: https://pastebin.com/2cB6A3NA

## Expected behavior
Being able to build and play the mod "out of the box".

**Comment by thedarkcolour** [comment]
Mod should compile now. I'll look at the CCL next

**Comment by thedarkcolour** [comment]
FutureMC will still work on forge 2847

**Comment by Su5eD** [comment]
There's a gradle plugin available that adds patches for the mentioned issues - [FancyGradle](https://gitlab.com/gofancy/fancygradle).  
It's pretty simple to use - the plugin id is `wtf.gofancy.fancygradle`, and it's available on gitlab packages [maven](https://gitlab.com/api/v4/projects/26758973/packages/maven).
Patches can be applied using:
```gradle
import wtf.gofancy.fancygradle.patch.Patch

fancyGradle {
    patches {
        patch(Patch.RESOURCES, Patch.COREMODS, Patch.CODE_CHICKEN_LIB, Patch.ASM)
    }
}
```
You can find a working example [here](https://github.com/Su5eD/GraviSuitePatcher/blob/master/build.gradle.kts).

Regarding the FG version, 3 will soon become EOL with the release of forge for 1.17. You can switch to FG5 and use Gradle 7 with the latest features.

**Comment by thedarkcolour** [comment]
Alright it should work now
