### ISSUE TITLE
[1.12.2] Blast Furnace and Smoker break with crafttweaker

### ISSUE THREAD

**Issue by throaway123869** [thedarkcolour/Future-MC#251]
When I did this:
Furnace: Iron ore > Iron nugget
Blast Furnace: Iron ore > iron ingot
I still got the iron nugget from the blast furnace. This happened in all recipes where the furnace and blast furnace smelted the same item into two different things.  Additionally, all crafttweaker recipes added to the smoker outputted no items at all.

**Comment by thedarkcolour** [comment]
Unfortunately you cannot remove recipes from smoker and blast furnace. I'm going to add a config option next update to disable the auto adding of smoker/ blast furnace recipes which will fix the issue of being stuck with vanilla recipes.

**Comment by democat3457** [comment]
Related to #80 (bug) #217 (bug) #232 (request)

**Comment by thedarkcolour** [comment]
I'll add a config option and mention it in the CraftTweaker wiki

**Comment by democat3457** [comment]
wow theres actually a lot of related issues

**Comment by throaway123869** [comment]
It's important to note that on the Wiki there are methods to remove blast furnace and smoker recipes.  Are these not functioning or bugged?

**Comment by thedarkcolour** [comment]
They're bugged but I'll update with new information
