### ISSUE TITLE
[1.12.2] Bees Incompatible With OTG Worlds

### ISSUE THREAD

**Issue by SaltSouls** [thedarkcolour/Future-MC#256]
Bees nests will not spawn in OTG worlds even when adding their biome to the biome list. Not sure if this is because of OTGs custom trees or the way they do their biomes, but currently they never spawn, making it impossible to get the items.

**Comment by Macleykun** [comment]
heya, that's true it's already adressed here: https://github.com/thedarkcolour/Future-MC/issues/86
I did ask a friend of mine if he has the time to look at it. I though thedarkcolour was also looking at it (or even had some progress done)

**Comment by Macleykun** [comment]
I talked with my friend, but the owner already made a bit of progress but isn't able to get around it.
I suggest you follow this issue: https://github.com/thedarkcolour/Future-MC/issues/86 and close this one :-)

**Comment by thedarkcolour** [comment]
Right
