### ISSUE TITLE
[1.12.2] Blast Furnace and Smoker Crafttweaker...

### ISSUE THREAD

**Issue by throaway123869** [thedarkcolour/Future-MC#259]
If recipes are created to only exist in the blast furnace, but not the vanilla furnace, the blast furnace will output nothing.  This also happens with the smoker.  Curiously, if the furnace is set to create one output, and the blast furnace to create a different output, both from the same input item, the blast furnace will always output what the furnace outputs.  I think the issue of the blast furnace and smoker bug that was supposedly fixed still exists in 0.2.7.1.

**Comment by SaltSouls** [comment]
That and adding a recipe to the smoker seems to add it to the blast furnace even if it is also currently being removed from the blast furnace.
