### ISSUE TITLE
[1.12.2] CRT OreDict cannot find item

### ISSUE THREAD

**Issue by joe-vettek** [thedarkcolour/Future-MC#263]
When I use oredict to modify the composter, it cannot match the leaf saplings of the forestry mod, nor can it match the item of the foodfunk mod. Only IItemStack works, but this is too much trouble. .

**Comment by democat3457** [comment]
in the meantime, you can do something like this:
```
for item in <ore:treeLeaves>.items {
  mods.futuremc.Composer.addValidItem(item, 30);
}
```
but this is by no means a permanent solution

**Comment by thedarkcolour** [comment]
I'll look at it this weekend

**Comment by joe-vettek** [comment]
I just tried it again. When I set the probability to 35, it is displayed as 32 in jei. If it is 65, it is displayed as 64. The previous setting is 30 and it is displayed as 4.

**Comment by democat3457** [comment]
what error

**Comment by joe-vettek** [comment]
A bunch of numbers will come out, I don’t know what it means.

**Comment by joe-vettek** [comment]
[log.txt](https://github.com/thedarkcolour/Future-MC/files/7448886/log.txt)

**Comment by joe-vettek** [comment]
![code](https://user-images.githubusercontent.com/82761814/139585306-eefd57bc-3e18-4297-8e08-746cb543de97.png)

**Comment by joe-vettek** [comment]
Only the method I said before is effective. Some mod items need to specify ID and metadata to add. It is currently known that Forestry and Food Funk need to do this.

**Comment by democat3457** [comment]
@joe-vettek oh it seems like I made a typo LOL whoops - I put `Composer` instead of `Composted`, which is why

I edited my original post to fix it

**Comment by thedarkcolour** [comment]
Could you send an example CraftTweaker script for what you want to be able to accomplish?

**Comment by joe-vettek** [comment]
I'll try, because I can't find my script.

**Comment by joe-vettek** [comment]
//// mods.futuremc.Composter.addValidItem(IItemStack item, int chance);


//foodfunk
//mods.futuremc.Composter.addValidItem(<foodfunk:rotten_food:0>, 100);
//mods.futuremc.Composter.addValidItem(<foodfunk:biodegradable_item:0>, 100);

//sakura
//mods.futuremc.Composter.addValidItem(<sakura:foodset>, 85);

//forestry
mods.futuremc.Composter.addValidItem(<ore:fruitForestry>, 65);
mods.futuremc.Composter.addValidItem(<forestry:sapling:0>, 35);
mods.futuremc.Composter.addValidItem(<botany:itemflower:0>, 65);
mods.futuremc.Composter.addValidItem(<forestry:leaves.decorative.2:0>, 35);
mods.futuremc.Composter.addValidItem(<forestry:leaves.decorative.2:1>, 35);
mods.futuremc.Composter.addValidItem(<forestry:leaves.decorative.2:2>, 35);
mods.futuremc.Composter.addValidItem(<extratrees:leaves.decorative.6:0>, 35);

val botanyPlant = <botany:plant>.definition;
for i in 0 to 4 {
mods.futuremc.Composter.addValidItem(botanyPlant.makeStack(i), 35);}

val extratreesFood = <extratrees:food>.definition;
for i in 0 to 59 {
mods.futuremc.Composter.addValidItem(extratreesFood.makeStack(i), 65);}

val forestryLeaves = <forestry:leaves.decorative.1>.definition;
val extratreesLeaves0 = <extratrees:leaves.decorative.0>.definition;
val extratreesLeaves1 = <extratrees:leaves.decorative.1>.definition;
val extratreesLeaves2 = <extratrees:leaves.decorative.2>.definition;
val extratreesLeaves3 = <extratrees:leaves.decorative.3>.definition;
val extratreesLeaves4 = <extratrees:leaves.decorative.4>.definition;
val extratreesLeaves5 = <extratrees:leaves.decorative.5>.definition;
for i in 0 to 15 {
mods.futuremc.Composter.addValidItem(forestryLeaves.makeStack(i), 35);
mods.futuremc.Composter.addValidItem(extratreesLeaves0.makeStack(i), 35);
mods.futuremc.Composter.addValidItem(extratreesLeaves1.makeStack(i), 35);
mods.futuremc.Composter.addValidItem(extratreesLeaves2.makeStack(i), 35);
mods.futuremc.Composter.addValidItem(extratreesLeaves3.makeStack(i), 35);
mods.futuremc.Composter.addValidItem(extratreesLeaves4.makeStack(i), 35);
mods.futuremc.Composter.addValidItem(extratreesLeaves5.makeStack(i), 35);

}

//

//ore

mods.futuremc.Composter.addValidItem(<ore:listAllveggie>, 65);
mods.futuremc.Composter.addValidItem(<ore:listAllfruit>, 65);
mods.futuremc.Composter.addValidItem(<ore:listAllSeed>, 65);
mods.futuremc.Composter.addValidItem(<ore:treeLeaves>, 35);
mods.futuremc.Composter.addValidItem(<ore:treeSapling>, 35);
mods.futuremc.Composter.addValidItem(<ore:plant>, 65);



//PMP
//mods.futuremc.Composter.addValidItem(<ore:foodBerry>, 65);
//mods.futuremc.Composter.addValidItem(<ore:foodFruit>, 65);
//mods.futuremc.Composter.addValidItem(<ore:foodNut>, 65);
//mods.futuremc.Composter.addValidItem(<ore:foodVegetable>, 65);

**Comment by joe-vettek** [comment]
It works.

**Comment by thedarkcolour** [comment]
Should I close the issue?

**Comment by democat3457** [comment]
if it works, then i  suppose  so

**Comment by thedarkcolour** [comment]
I'm broadening the CraftTweaker functions to use all IIngredient, so IOreIngredient and IItemStack should work for the same functions now.
