### ISSUE TITLE
Grindstone dupe 

### ISSUE THREAD

**Issue by futurenp** [thedarkcolour/Future-MC#27]
When shift clicking an item into the grindstone and exiting at almost the same time, the item will dupe.

**Comment by Fireztonez** [comment]
Dupe bug confirm on Future MC 0.1.8b.

I try with an enchanted diamond pickaxe, I place in the grindstone end I quid instantly the interface, I get back the pickaxe into my inventory and when I reopen my inventory, I saw a new identical pickaxe drop on the floor!!

I can reproduce that indefinitely without any issue, this is a 100% chance of dupe...

**Comment by thedarkcolour** [comment]
I'll take a look at it.

**Comment by thedarkcolour** [comment]
Fixed in 0.1.9
