### ISSUE TITLE
[1.12.2] Dispenser shears Sheep with no wool dropped out

### ISSUE THREAD

**Issue by RisingInIris2017** [thedarkcolour/Future-MC#271]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2855
### Related Mods Version
Forgelin: 1.8.4
Future MC: 0.2.7.3
### How to reproduce
1. Put a shear into a dispenser.
2. Put a sheep in front of the dispenser.
3. Activate the dispenser with a redstone pulse signal.
4. Sheep is sheared, but no wool item is dropped out.

Thanks for your help in advance!
Looking forward to your reply.

**Comment by thedarkcolour** [comment]
Huh. It crashes for me
