### ISSUE TITLE
[1.12.2] Bees Pollinating on Grass

### ISSUE THREAD

**Issue by SaltSouls** [thedarkcolour/Future-MC#281]
It would seem that bees are treating grass blocks as a flower that they are able to pollinate. They will just hover around the ground for a little while and then fly back up to their hives.
I would suggest adding a config option(If not too difficult) for which blocks/flowers are able to be pollinated by bees.

**Comment by gatoborrachon** [comment]
> I would suggest adding a config option(If not too difficult) for which blocks/flowers are able to be pollinated by bees.

i think it actually exist, although i can't find it, i suggest you to ask this in his discord server: https://discord.com/invite/xtFWtm4

**Comment by thedarkcolour** [comment]
This is a bug, but you can change the blocks bees can pollinate using CraftTweaker

**Comment by thedarkcolour** [comment]
What mods are you using that the bees do this?

**Comment by thedarkcolour** [comment]
I will close this issue if no image/video proof or mods list is added.
