### ISSUE TITLE
Missing texture assigned to modded villager job zombies

### ISSUE THREAD

**Issue by exoRift** [thedarkcolour/Future-MC#283]
When a villager has a job from a mod and becomes a zombie villager, FMC attempts to assign a texture to it, resulting in a missing texture.

![image](https://user-images.githubusercontent.com/20345400/149687357-72e37c82-a92e-43f9-8b11-adf820bfc0b6.png)

**Comment by thedarkcolour** [comment]
I don't think this is caused by FMC. Is this all modded villagers or only specific mods?

**Comment by exoRift** [comment]
It seems so

**Comment by thedarkcolour** [comment]
?

**Comment by democat3457** [comment]
(it got edited)

**Comment by exoRift** [comment]
Nevermind, it was, in fact, a specific mod. I apologize for bothering you
