### ISSUE TITLE
Errors when disabling items/blocks in the config

### ISSUE THREAD

**Issue by MrAkells** [thedarkcolour/Future-MC#285]
Here is a simple example, full logs are also attached
https://pastebin.com/xBfAP5Rh

![2022-01-25_03-06](https://user-images.githubusercontent.com/64635280/150879899-84f3063f-debd-414b-a925-ee5fcac6782a.png)

**Comment by thedarkcolour** [comment]
I can't do anything about this as far as I'm aware

**Comment by MrAkells** [comment]
> I can't do anything about this as far as I'm aware

Weird. Haven't seen this error in any other mod. Can you describe the cause of this error?

**Comment by thedarkcolour** [comment]
Minecraft loads recipes from inside the Future MC mod jar and it prints these errors if the items don't exist (are disabled). Minecraft loads the recipe files, not Future MC, so I don't know how to avoid loading files with disabled items in them
The errors don't affect gameplay, so I wouldn't worry about it

**Comment by MrAkells** [comment]
> Minecraft loads the recipe files, not Future MC

It seems to me that the reason for this error lies in the fact that you are loading crafting recipes using vanilla-style json files. The same quark does it differently, introduces recipes for items and blocks. As part of his jar file, there is simply no folder with recipes.

**Comment by thedarkcolour** [comment]
I don't feel that hiding innocuous error messages is worth rewriting these recipes in code, sorry.

**Comment by MrAkells** [comment]
> 
There is an error, and you close the issue ...

**Comment by thedarkcolour** [comment]
The error doesn't impact gameplay at all and it's not worth the effort
