### ISSUE TITLE
Campfire is non-functioning

### ISSUE THREAD

**Issue by SusannaEStott** [thedarkcolour/Future-MC#29]
Attempted to place campfire in creative mode on the ground, and it displays properly, but I cannot place any food items on it. Is it usable or purely decorative right now?   Also tried in a purely survival world and it still doesn't function.

**Comment by thedarkcolour** [comment]
It is purely decorative atm. I forgot about that, thanks!

**Comment by futurenp** [comment]
also this isnt in vanilla, but maybe you could add a config file to allow hoppers to function with campfires?

**Comment by thedarkcolour** [comment]
@SusannaEStott @futurenp I'm currently testing functionality with Campfires. Things aren't rendering right now, but it cooks things.

**Comment by SusannaEStott** [comment]
Thanks for your reply! I somehow missed the first one however long ago that
was... also, thank you for developing this mod. It's very handy and I love
it!

**Comment by thedarkcolour** [comment]
Stuff renders now, and stuff shows up in JEI recipes now. However, I'm getting an issue where it spawns way too much food.

**Comment by thedarkcolour** [comment]
Fixed in 0.1.12
