### ISSUE TITLE
Game crashes when using stonecutter

### ISSUE THREAD

**Issue by fincherly** [thedarkcolour/Future-MC#292]
pretty much what the title says, i can right click the stonecutter fine but as soon as i try to put anything in it the game freezes and crashes. as far as i know im using the most recent updated version on curseforge (0.2.8) (ive tried going for older builds too but no luck) -- i dont know enough about coding to pinpoint what's up with it
here's a screenshot of the error:

![Screenshot (13)](https://user-images.githubusercontent.com/102340604/160048992-12ec0e8b-fe60-4f7f-9e7b-006add1fd24e.png)

the stonecutter isnt really a strictly necessary thing so i can survive without, but it did eat a stack of prismarine :(

**Comment by thedarkcolour** [comment]
Send the whole crash report

**Comment by thedarkcolour** [comment]
You can upload it through [GitHub gists](https://gist.github.com/)

**Comment by fincherly** [comment]
whoops sorry! here: https://gist.github.com/fincherly/af26438f53402ec1f84268695c05cf9b

**Comment by embeddedt** [comment]
Your Quark version appears to be very old. I think this crash will go away if you update to the [latest version](https://www.curseforge.com/minecraft/mc-mods/quark/files/2924091).

**Comment by fincherly** [comment]
> Your Quark version appears to be very old. I think this crash will go away if you update to the [latest version](https://www.curseforge.com/minecraft/mc-mods/quark/files/2924091).

that's the same one i have actually ;-;

**Comment by embeddedt** [comment]
According to your log, you have `Quark-r1.3-117.jar` which is not the same version.

**Comment by fincherly** [comment]
oh man that's werid, both on the server and in my mods folder i have 1.6 179 ?? huh. not sure how to fix that

**Comment by embeddedt** [comment]
It might be worth triple-checking that you're looking at the right mods folder; I can't think of any reason why the crash report would give the wrong JAR name. For example, try moving the 1.6 JAR out of the mods folder you're looking at, then launch the pack again. If Quark isn't missing in-game you'll know it's the wrong folder.

**Comment by thedarkcolour** [comment]
Could always redownload the mod jar
