### ISSUE TITLE
[1.12.2] Issue with trying to load recipes for disabled features

### ISSUE THREAD

**Issue by throaway123869** [thedarkcolour/Future-MC#294]
In the log file, this is seen:
https://paste.ee/p/LwEXE

Looks like futuremc is trying to load recipes for blocks that I disabled in the config, which puts the above stuff in the log.  Not really a huge issue, but I figured the less log "spam", the better

**Comment by thedarkcolour** [comment]
Minecraft loads the recipes I can't fix that

**Comment by thedarkcolour** [comment]
I would have to take all of the recipe files and rewrite them in code manually. it's not worth the effort
