### ISSUE TITLE
Pandas should attack players after you attack one

### ISSUE THREAD

**Issue by Fireztonez** [thedarkcolour/Future-MC#30]
Hello,
I just test the Pandas in my modpack, it look amazing, really similar to pandas in minecraft 1.14, but when you attack in minecraft 1.14, pandas will attack you back like Bears does, but Pandas is completely inoffensive with Future MC. I think you should look to implement that feature aswell in Future MC. And by the way, there have a special faces for when pandas get agro on minecraft 1.14!!

**Comment by thedarkcolour** [comment]
There have been some issues with getting them to attack properly, I'll look into it. Sorry about the update taking so long, I have been burned out on working on Future MC. Don't worry, I'll get a patch out!

**Comment by thedarkcolour** [comment]
Fixed in 0.1.9b

**Comment by Fireztonez** [comment]
Thank's
Sincerely, you are really good for update, so much mods take mouths to make a small patch or never fix it!!
So continue like this!!
