### ISSUE TITLE
[1.12.2] OTG + Far From Home + Biomes o Plenty - Crash

### ISSUE THREAD

**Issue by DGTLC** [thedarkcolour/Future-MC#300]
The game crashes while creating or joining the world.

FutureMC Version: "0.2.9"
OTG Version: "v9.4"
Far From Home Version: "6.1"
Biomes o Plenty Version: "7.0.1.2445"

CrashLog: https://pastebin.com/UPYu69yA
Log: https://pastebin.com/LxhLWbZf

**Comment by thedarkcolour** [comment]
Can you test a fixed jar if I send you the link?

**Comment by DGTLC** [comment]
Yes

**Comment by thedarkcolour** [comment]
[Try this jar](https://drive.google.com/uc?export=download&id=1tjvVHt8GC7zYNEBJ0lX-q3YvOJIZfBnb)

**Comment by KuroNeko87** [comment]
Had same crash, tested possible fixed jar, game won't start. Might be because of some other mod but I got this https://paste.ee/p/WCSMH with that version.
