### ISSUE TITLE
[1.12.2] Future-MC + Ambience - Extras Crash

### ISSUE THREAD

**Issue by Ferisia** [thedarkcolour/Future-MC#301]
The game crashes after spending some time in a world.

FutureMC Version: [0.2.9]
Ambience - Extras [1.7.8]

Crash Log:
[crash-2022-06-03_17.46.28-server.txt](https://github.com/thedarkcolour/Future-MC/files/8833888/crash-2022-06-03_17.46.28-server.txt)

**Comment by thedarkcolour** [comment]
This is an Ambience bug that happens when a player is hurt by a Sweet Berry Bush. Unfortunately, this is an issue I cannot fix on my side without removing berry bush damage.
