### ISSUE TITLE
Trying to make a ressource pack, futuremc textures not working

### ISSUE THREAD

**Issue by xeats** [thedarkcolour/Future-MC#304]
I'm making a ressource pack for 1.12.2 which includes futuremc 0.2.8.
Everything works fine, but textures are not working for this mod.

I've created the following folders in my ressource pack : futuremc/textures/blocks/ancient_debris.png and netherite_block.png, none of them are working.

**Comment by thedarkcolour** [comment]
Gotta love 1.12 naming conventions.
