### ISSUE TITLE
When Trident is disabled in configuration, elder guardians still attempt the drop

### ISSUE THREAD

**Issue by Asstuba** [thedarkcolour/Future-MC#31]
From what I can tell, ItemPhysics Full+CreativeCore are catching a null exception when an elder guardian is killed, when this is set in the future-mc configuration:

    B:ItemTrident=false

Because the item is still dropping.  It's not listed under the loot table of the elder guardian, if I export loot_tables/minecraft/entities/elder_guardian.  Yet it is still visibly dropping in game, so I'm guessing the loot doesn't function in the Vanilla-way, thus it's creating it in game via an event, which is triggering regardless of disabling the Trident or not, so when ItemPhysics tries to render the item, it's attempting to access a null value.

[crash-2019-07-21_15.18.58-server.txt](https://github.com/thedarkcolour/Future-MC/files/3415138/crash-2019-07-21_15.18.58-server.txt)

Here's Minecraft without ItemPhysics+CreativeCore, spawning two null items in world on the elder guardians death, and then running into them:

[crash-2019-07-21_15.23.54-server.txt](https://github.com/thedarkcolour/Future-MC/files/3415139/crash-2019-07-21_15.23.54-server.txt)

**Comment by thedarkcolour** [comment]
Oooh thanks for spotting this one!

**Comment by thedarkcolour** [comment]
Fixed in 0.1.9
