### ISSUE TITLE
[1.12.2] Trident is not thrown properly

### ISSUE THREAD

**Issue by ElLiox** [thedarkcolour/Future-MC#310]
With Future-mc-0.2.11 and Forgelin-1.8.4 with no other mods added. The trident is thrown to random directions. It never heads in the direction you're looking. This behavior is not replicated when the Riptide enchantment is used

**Comment by xkforce** [comment]
I dont know if I'd say it isnt replicated with riptide so much as it isn't throwable at all with riptide

**Comment by thedarkcolour** [comment]
Trident now throws properly but isn't fully complete.
