### ISSUE TITLE
[1.12.2] 49 errors when importing to intellij

### ISSUE THREAD

**Issue by DKIncorporatedIsTaken** [thedarkcolour/Future-MC#315]
log: 
[log.txt](https://github.com/thedarkcolour/Future-MC/files/9921560/log.txt)

**Comment by thedarkcolour** [comment]
Follow the setup guide for Forge 1.12 online. Run `setupDecompWorkspace` and `setupDevWorkspace` to get it working.

**Comment by DKIncorporatedIsTaken** [comment]
Still doesn't work
![Zrzut ekranu z 2022-11-02 16-06-49](https://user-images.githubusercontent.com/112394498/199526048-780161c3-0299-473c-92a6-3568d92c176d.png)

**Comment by thedarkcolour** [comment]
Try loading the project with the mod dependencies commented out first. Then reload the project with all the dependencies.

**Comment by DKIncorporatedIsTaken** [comment]
Thanks, it works now
