### ISSUE TITLE
[1.12.2] Grindstone Dupe Issue

### ISSUE THREAD

**Issue by platinumphoenix2** [thedarkcolour/Future-MC#317]
The Grindstone can duplicate items.

To reproduce:
Put an enchanted Iron Chesplate in one slot and an unenchanted Iron Chestplate in the other - make sure they have both full durability.
Shift click the output Iron Chestplate - - your inventory will be filled with Iron Chestplates.

Tested on: Future MC 1.12.2 0.2.11

**Comment by thedarkcolour** [comment]
I cannot reproduce this. What other mods do you have installed?

**Comment by platinumphoenix2** [comment]
This mod causes the issue: https://www.curseforge.com/minecraft/mc-mods/lolasm
This bug no longer occurs in their latest version (v5.6) - just updated it and tested it right now.

I have to use an outdated version of lolasm (v4.13) due to their latest version being incompatible with many mods in my modpack - and that's where this bug happens.

Sorry for the confusion!

**Comment by thedarkcolour** [comment]
Unfortunately, the version of LolAsm you're describing is no longer on CurseForge. I can't test this, and even if I could, it isn't worth it to bugfix an old version of a mod which has already been updated with a fix.
