### ISSUE TITLE
Grindstone dupe still present

### ISSUE THREAD

**Issue by futurenp** [thedarkcolour/Future-MC#32]
The latest update made it harder to do but it is still present in the latest update

A video of this happening is here https://drive.google.com/file/d/1mnt1h7DUZRR7QJa24UbwxbXySp9KpBAz/view?usp=sharing

You have to press escape almost immediately after clicking but it still works.

Edit: I found that this works even easier as you can just press both esc and click at the same time.
Edit 2: I found that all you need to do is hover an item in the grindstone's gui and hit esc and the item will dupe 100% of the time.

**Comment by thedarkcolour** [comment]
Fixed in 0.1.9b. I had it fixed at one point, but the Grindstone wasn't disenchanting items. I copy pasted what I had from a previous update and forgot to re-fix the glitch. It should work properly this time.
