### ISSUE TITLE
[1.12.2] Bees will not leave the hive unless blocked.

### ISSUE THREAD

**Issue by Slayer5934** [thedarkcolour/Future-MC#320]
https://github.com/thedarkcolour/Future-MC/blob/main/src/main/java/thedarkcolour/futuremc/tile/BeeHiveTile.kt

You can see here that
`val flag = isExitBlocked(world, pos1)`
checks for if the block is blocked right?

and 
```
if (flag && beeState != BeeState.EMERGENCY) {
                return false
```
makes it so the bees do not come out unless it is not blocked

well 
```
private fun isExitBlocked(worldIn: World, pos: BlockPos): Boolean {
        return worldIn.getBlockState(pos).isAir(worldIn, pos)
    }
```
returns a true value when it is *not* blocked.

So bees cannot exit the hive unless the entrance is blocked.

**Comment by thedarkcolour** [comment]
You're correct

**Comment by Slayer5934** [comment]
I can do that :p

**Comment by Slayer5934** [comment]
https://github.com/thedarkcolour/Future-MC/pull/321
