### ISSUE TITLE
[1.12.2][Request] Auto-disable Aquatic Update backports if Oceanic-Expanse is installed

### ISSUE THREAD

**Issue by vico93** [thedarkcolour/Future-MC#324]
More like a convenience suggestion, similar to how Quark behaves if mods that add similar features/mechanics are present in the pack.

Basically, auto-disable (regardless of the values on config) all features that are in common with [Oceanic-Expanse](https://modrinth.com/mod/oceanic-expanse) ([GH](https://github.com/SirSquidly/Oceanic-Expanse)), another mod focused in backport features from 1.13 but with a twist to have also brand new stuff based on those.

**Comment by thedarkcolour** [comment]
Added in 0.2.18
