### ISSUE TITLE
[1.12.2] Honey bottle is broken

### ISSUE THREAD

**Issue by LonelyxiyaOVO** [thedarkcolour/Future-MC#334]
Subaquatic and futuremc incompatible 
clash
[crash-2023-12-30_09.07.49-client.txt](https://github.com/thedarkcolour/Future-MC/files/13796732/crash-2023-12-30_09.07.49-client.txt)
[crash-2023-12-30_09.09.33-client.txt](https://github.com/thedarkcolour/Future-MC/files/13796733/crash-2023-12-30_09.09.33-client.txt)

**Comment by thedarkcolour** [comment]
Can you send the whole log file?

**Comment by LonelyxiyaOVO** [comment]
[2023-12-30-4.log.gz](https://github.com/thedarkcolour/Future-MC/files/13796793/2023-12-30-4.log.gz)
[2023-12-30-5.log.gz](https://github.com/thedarkcolour/Future-MC/files/13796794/2023-12-30-5.log.gz)

**Comment by thedarkcolour** [comment]
Fixed in 0.2.13
