### ISSUE TITLE
0.2.12 crash with Prehistoric Nature

### ISSUE THREAD

**Issue by B-Wither** [thedarkcolour/Future-MC#335]
[crash-2023-12-30_12.16.49-server.txt](https://github.com/thedarkcolour/Future-MC/files/13796963/crash-2023-12-30_12.16.49-server.txt)
[latest.log](https://github.com/thedarkcolour/Future-MC/files/13796966/latest.log)

**Comment by thedarkcolour** [comment]
This is actually the same issue as #334
