### ISSUE TITLE
[1.12.2]Issues in Version 0.2.13

### ISSUE THREAD

**Issue by LonelyxiyaOVO** [thedarkcolour/Future-MC#336]
After updating to version 0.2.13, an error occurred. The log is as follows:
[crash-2023-12-30_21.00.30-client.txt](https://github.com/thedarkcolour/Future-MC/files/13799439/crash-2023-12-30_21.00.30-client.txt)
[latest.log](https://github.com/thedarkcolour/Future-MC/files/13799440/latest.log)

**Comment by thedarkcolour** [comment]
This is not a FutureMC issue

**Comment by thedarkcolour** [comment]
Related to TechReborn instead
