### ISSUE TITLE
Crashing (going back to main menu) when opening Villager's inventory

### ISSUE THREAD

**Issue by InterPlay02** [thedarkcolour/Future-MC#337]
Hi...

I don't know if you still updating this mod, but afterr I've updated to the latest version of the mod, the game started crashing and going back to main menu whenever I open a villager trading UI.

Here is the log file:
https://github.com/InterPlay02/Random-Codes/blob/principal/CTMM%20Future%20MC.log

This is the long version. The error appears at the bottom of the log file. Well... you already know that.

I hope you have a happy new year.

**Comment by thedarkcolour** [comment]
I wonder why these crashes never happened before. I don't recall changing any of the code.

**Comment by thedarkcolour** [comment]
Fixed in 0.2.14
