### ISSUE TITLE
1.12.2 FutureMC crashes on Worldgen.

### ISSUE THREAD

**Issue by toErIpNid** [thedarkcolour/Future-MC#338]
Crash Log: https://mclo.gs/HQ0wEYc

Mod Ver: 2.15

Forge Ver: 2860

**Comment by thedarkcolour** [comment]
Can you reproduce this with only Future MC?

**Comment by toErIpNid** [comment]
No I cannot. It's a mod conflict.

**Comment by thedarkcolour** [comment]
Unfortunately I cannot tell which mods cause the conflict. Are you able to narrow down which mods are conflicting?

**Comment by toErIpNid** [comment]
I'll see what I can do here later on.

**Comment by toErIpNid** [comment]
Okay, so I think I figured out which mod is causing the crash. https://www.curseforge.com/minecraft/mc-mods/sledgehammer
When this is placed in the pack, FutureMC and a few others crash on worldgen.

**Comment by thedarkcolour** [comment]
Open an issue on that mod's GitHub then.
