### ISSUE TITLE
Issues when disabling some items

### ISSUE THREAD

**Issue by Gavintime** [thedarkcolour/Future-MC#34]
If lanterns are disabled in the config the creative menu tab icon is blank, a fallback vanilla item could be used as the icon

If smooth stone is disabled, blast furnaces have no fall back recipe

When craftable items are disabled, their recipes don't get disabled properly, in game this doesn't seem to be an issue, but it does throw errors in the log of being unable to make the recipes

**Comment by thedarkcolour** [comment]
The recipes are json, so I can't really toggle them. I'll deal with the tab issue.

**Comment by thedarkcolour** [comment]
Fixed in 0.1.10
