### ISSUE TITLE
Successful Application of Game Mode Converter

### ISSUE THREAD

**Issue by krzj** [thedarkcolour/Future-MC#346]
https://github.com/MBYL-InkAndSoul/Modern-Gamemode-Switcher

**Comment by Titoo8899** [comment]
Oh this mod have I and I have the Version 1.2 of this Modern-Gamemode-Switcher Mod with the Minecraft Design what nice is and a rare mod version is the owner have this version deleted for a safe of the new EULA of Mojang

**Comment by thedarkcolour** [comment]
I don't need to copy another implementation, I just have to fix mine and add the graphic
