### ISSUE TITLE
Gamemode Switcher is good but  a little detail was missed and the last Switch Position was not hold

### ISSUE THREAD

**Issue by Titoo8899** [thedarkcolour/Future-MC#349]
Original Design:
![ezgif com-webp-to-png](https://github.com/thedarkcolour/Future-MC/assets/42325138/5fb2728f-449d-46ae-9276-002cbd986b7f)
hi, 

I have your mod test and the newest version was good and work but one little think I miss on the GUI of the Gamemode Switcher and hope you can this add on the GUI. Then I the F3 press and with F4 then the gamemmode switch the word (F4) is good but behind of the (F4) is the world "next". The Original Design have " [ F4 ] Next " I hope you can this little change in the next update add.

And the Other Problem is the Gamemode Switcher GUI hold not the last position of the Button. Then I go from Creative and switch to Advanture Mode the GUI hold not the Position what my last change was. Then I now press F3 + F4 the GUI start from the  first position and I muss 3X press the F4 button to go to the Spectator Mode. I hope you can change this to press only F3+ F4 so you can faster to the next Gamemode switch

**Comment by thedarkcolour** [comment]
I'll make the first change, but not the second. You're right that I missed the "next" part of the text, that was me rushing. The second part you're suggesting is not Vanilla behavior, so I won't be adding it.
