### ISSUE TITLE
Composter configuration

### ISSUE THREAD

**Issue by UncleSam139** [thedarkcolour/Future-MC#36]
You have added the composter from Minecraft 1.14. 

Therefore, I have an inquiry and that is about the composter itself. Would it be possible to make the composter configurable? This means that you can set what is compostable and what it outputs.

This would be a nice extension.

**Comment by thedarkcolour** [comment]
You can change compostable items using CraftTweaker. I am not going to add custom outputs, as that was not how it was implemented in 1.14.
