### ISSUE TITLE
Stripped log bug

### ISSUE THREAD

**Issue by Kuwagumo** [thedarkcolour/Future-MC#368]
It seems that after one of the updates, the stripped logs entries were removed, but it's still possible to right click logs with an axe in order to strip them, leaving a no texture block with no properties, as if it was air. It crashes too soon after.

**Comment by thedarkcolour** [comment]
Are you using Oceanic Expanse?

**Comment by thedarkcolour** [comment]
Duplicate of #359

**Comment by Kuwagumo** [comment]
> Are you using Oceanic Expanse?

yes! that's what i discovered. Fixed it by disabling the compat. Sorry for the bother!

**Comment by thedarkcolour** [comment]
Don't worry. It will be fixed next update.
