### ISSUE TITLE
CraftTweaker IIngredient support (For OreDict and more)

### ISSUE THREAD

**Issue by Fireztonez** [thedarkcolour/Future-MC#40]
Hello,
I just look the CraftTweaker support for the composter, the Smoker and the Blast Furnace and you support only input IItemStack, can you please look question to change for using IIngredient instead, at least for being able to use OreDict entry for the item input?

This way I will be able to add directly all seeds from the game in one line, and not like 100 lines... Sames for ores with ores from multiple dimensions or different mods.

Thank's
Fireztonez

**Comment by thedarkcolour** [comment]
I'll put an update out with this.

**Comment by thedarkcolour** [comment]
Fixed in 0.1.10
