### ISSUE TITLE
Request - Blast Furnace and Smoker recipes with specified output

### ISSUE THREAD

**Issue by Fireztonez** [thedarkcolour/Future-MC#41]
Hello,
I just saw the Blast Furnace and Smoker crafttweaker support doesn't allow the specified the output for a specific input. I think you should add the possibility to choose the output and not just the input.

By example, in my modpack, when you cook any ores in a furnace you get only 2 nuggets, but in the blast furnace you still get 1 ingot... Presently, there have no way with the crafttweaker support to fix that issue...

Thank's

**Comment by thedarkcolour** [comment]
What mod are you using to change the original furnace recipes? I use the exact same recipes as the regular furnace, and my CraftTweaker functions allow for whitelisting certain furnace recipes so that the Blast Furnace is not restricted to ore recipes.

**Comment by thedarkcolour** [comment]
You shouldn't need to add specific outputs to the blast furnace, as it is not a separate machine from the  furnace. If all was working as intended, recipes you change in the normal furnace would also change in the Blast Furnace / Smoker.

**Comment by Fireztonez** [comment]
Oki, this is completly my bad... I just test to cook an Iron Ore Cluster in the Blast Furnace and it give me only 2 nuggets, but when I cook an Iron Ore Block, I get 1 ingot instead, but I test in the furnace and it does the same. So, I think, the problem is with my Crafttweaker script for changing the furnace recipes... Look like i use IItemStack instead of using OreDict entries...

Sorry to open that issue for a bug in my modpack, and not with with your mod.
