### ISSUE TITLE
Bamboo hitbox is off from the model

### ISSUE THREAD

**Issue by megoesrawr** [thedarkcolour/Future-MC#43]
The model is off from the hitbox in the newest version of the mod.
![2019-08-05_17 05 00](https://user-images.githubusercontent.com/7830406/62495327-8dea3700-b7a3-11e9-9626-9deb861b6db5.png)
related to: #33

**Comment by thedarkcolour** [comment]
I can't reproduce this... one of your mods must be messing up the random placement offset.

**Comment by Gavintime** [comment]
This issue happens when OptiFine 1.12.2 HD U E3 (latest) is installed.

**Comment by thedarkcolour** [comment]
Ohhhh.

**Comment by thedarkcolour** [comment]
I have reproduced it. It turns out that OptiFine fixes flower hitboxes, and that fix seems to have carried over to the bamboo block. I will fix it by next update.

**Comment by thedarkcolour** [comment]
I have the fix! It's coming next update.

**Comment by thedarkcolour** [comment]
Fixed 0.1.11
