### ISSUE TITLE
Trident too op when out of water

### ISSUE THREAD

**Issue by futurenp** [thedarkcolour/Future-MC#44]
Trident when having impaling will work when it is not raining and out of water.
It should only use impaling when the player is 'wet'

**Comment by thedarkcolour** [comment]
That's not how impaling works. However, I feel like I want to take the Bedrock Edition approach to which mobs it should increase damage against (all mobs).

**Comment by futurenp** [comment]
![image](https://user-images.githubusercontent.com/52610746/63149552-1ea5eb80-bfca-11e9-8aa9-cea9d6a9fd38.png)
