### ISSUE TITLE
Trident and Enchantment table

### ISSUE THREAD

**Issue by futurenp** [thedarkcolour/Future-MC#45]
In vanilla you are not able to put a trident into an enchantment table
In this you are able to and enchant it from there

**Comment by thedarkcolour** [comment]
I will fix

**Comment by futurenp** [comment]
Turns out this is intended in the vanilla game.
However I would still like to use this so maybe as a config to toggle?

**Comment by thedarkcolour** [comment]
Fixed in 0.1.11

**Comment by thedarkcolour** [comment]
I'll add a config in 0.1.12
