### ISSUE TITLE
Can you update 1.13 fish and coral..

### ISSUE THREAD

**Issue by Abo233** [thedarkcolour/Future-MC#46]
Feeling didn't update to the point

**Comment by thedarkcolour** [comment]
They redid fluid rendering in 1.13 so I can't get the oceans to look the same. I might try the coral reefs at some point.

**Comment by Abo233** [comment]
Can you update more entity fish
Unlike 1.13 it doesn't matter
Think only coral, no fish too drab...

**Comment by Abo233** [comment]
1.12 the mod now
Update only land creatures, all don't update the fish, good boring.

**Comment by Abo233** [comment]
Want to update more entity fish...

**Comment by thedarkcolour** [comment]
Are you able to speak English?

**Comment by Abo233** [comment]
NO

**Comment by Abo233** [comment]
Use the translator...

**Comment by thedarkcolour** [comment]
I got fish working so they'll be in the next update.

**Comment by thedarkcolour** [comment]
Since #17 contains all these requests I'll be closing the issue to make things simpler.
