### ISSUE TITLE
Trident does Impaling to mobs out of water

### ISSUE THREAD

**Issue by futurenp** [thedarkcolour/Future-MC#47]
![image](https://user-images.githubusercontent.com/52610746/63194845-a75a7100-c036-11e9-881d-1875667c7bef.png)

**Comment by futurenp** [comment]
https://minecraft.gamepedia.com/Impaling

**Comment by thedarkcolour** [comment]
Will fix

**Comment by thedarkcolour** [comment]
Fixed in 0.1.11
