### ISSUE TITLE
JEI Tooltip Error

### ISSUE THREAD

**Issue by SextupleTap** [thedarkcolour/Future-MC#49]
When you have the FutureMC dyes disabled, JEI still (somehow) detects the dyes and attempts to register them in recipes. Just load FutureMC with the dyes disabled and JEI will attempt to register the dyes that aren't actually enabled, resulting in a tooltip error showing because of the ore dictionary entry that the dyes have 'dyeColor.' All four dyes (black, brown, blue, white) cause this tooltip error and are attempted to still be registered by JEI.

FutureMC Verision 0.1.10 - JEI log information:
https://pastebin.com/QUMxLTLX

(You could perhaps keep an eye out to see if this happens with other items in your mod with ore dictionary entries, such as the flowers and if disabling them causes them to appear in a recipe as a 'tooltip error' that uses the 'plant' ore dictionary entry in its recipe, etc.)

**Comment by thedarkcolour** [comment]
Fixed in 0.1.11
