### ISSUE TITLE
Crash on a server end

### ISSUE THREAD

**Issue by Sunconure11** [thedarkcolour/Future-MC#51]
https://pastebin.com/XBiYNCke

**Comment by JCManzo** [comment]
Same error as well https://pastebin.com/Rv0MiDN4

Thanks for the upcoming fix!

**Comment by thedarkcolour** [comment]
I re-uploaded it with a fix on CurseForge.

**Comment by JCManzo** [comment]
I'm still experiencing this server crash at [Gui.java:36](https://pastebin.com/KnAvP2V8) now

**Comment by thedarkcolour** [comment]
I'll see what's wrong

**Comment by thedarkcolour** [comment]
I think I actually fixed it this time. Let me know if other stuff goes wrong! Check Future MC 0.1.11d.

**Comment by Scratchman** [comment]
still crashing with future MC 0.1.11 (_that is the name of the version that downloads from curseforge_)

same crash as OP.

[https://pastebin.com/rmU6w9vk](url)

**Comment by JCManzo** [comment]
Working fine for me with latest version MC 0.1.11d

**Comment by Scratchman** [comment]
well, i don't understand what the problem is then unless curseforge is not downloading version 0.1.11d.

when i click the link for version 0.1.11d, i download version 0.1.11 and with that version the server crashes.

**Comment by thedarkcolour** [comment]
The jar file is 0.1.11, I don't change it with hotfixes. Try re-downloading on curseforge, works fine on my end.
