### ISSUE TITLE
1.15 addon crash with Cubic Chunks mod?

### ISSUE THREAD

**Issue by wimplaw** [thedarkcolour/Future-MC#52]
0.1.11 seems to crash with cubic chunks instaled? 
As the 0.1.10 had no problems I tried disabling the 1.15 stuff in the config file, and this removed the crash problem. so it seems the problem is related to 1.15 addons.

[crash-2019-09-25_00.01.06-client.txt](https://github.com/thedarkcolour/Future-MC/files/3649743/crash-2019-09-25_00.01.06-client.txt)

**Comment by thedarkcolour** [comment]
0.1.11 currently replaces a few biomes and adds the beehives to the trees, so that is the issue. I'm not sure how to fix this, but I can look into it later.

**Comment by Barteks2x** [comment]
This is a bug in my code. I didn't expect registry substitutions. I will fix it soon.

**Comment by thedarkcolour** [comment]
@Barteks2x I am switching to an ASM coremod to get the beehives to generate.

**Comment by Barteks2x** [comment]
Honestly registry replacement looks like a correct way to do it. Still, coremod is probably going to be more compatible with anything that attempts to change something else about the same biomes (unfortunately there are a lot of cases where coremods may have better compatibility than doing something without a coremod).

**Comment by thedarkcolour** [comment]
Should be fixed now. I tested it and it doesn't crash anymore.
