### ISSUE TITLE
Twillight Forest/The Betweenlands crash.

### ISSUE THREAD

**Issue by bloodyearth** [thedarkcolour/Future-MC#56]
Hey. At first, everything worked fine for me. But then, for some reason, Minecraft began to crash on the loading screen.
I started sorting through the mods and noticed that this only happens when FutureMC is installed with Twillight Forest or The Betweenlands.

If you remove FutureMC, Minecraft turns on normally.

Or if you do not remove FutureMC, but remove Twillight Forest and The Betweenlands, the game also loads.

Crash:
https://hastebin.app/5d974b3d4798f8001c0daaa1

**Comment by bloodyearth** [comment]
UPD: I disabled the bees in the config and the load was successful.

Please fix this. We need bees. :)

**Comment by thedarkcolour** [comment]
It looks like I need to change beehive generation. :(

**Comment by thedarkcolour** [comment]
Fixed in 0.1.12
