### ISSUE TITLE
Compatibility with shaders

### ISSUE THREAD

**Issue by SlimF** [thedarkcolour/Future-MC#61]
A lot of, if not all, shaders make vanilla MC leaves and flowers move like as if there's wind in the game. The Cornflower, Lily of the Valley and Sweet Berries' IDs are not recognized by the shaders hence they do not wave like the rest of the plants and because of that they seem a bit out of place.

The Streams mod has built in customization for its water blocks, so it might be of help to see how the developer of the mod has done it.
[CurseForge](https://www.curseforge.com/minecraft/mc-mods/streams)
[Github](https://github.com/delvr/Streams)
[Minecraft Forum](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2346379-streams-real-flowing-rivers) - There's some info about implementing shader support in the FAQ

**Comment by SamuraiShogun1102** [comment]
I just hoped it’s compatible with obtifine E3

**Comment by mmmilord** [comment]
I don't believe the streams mod works with shaders, as the last time I had it installed, it wasn't rendering properly

**Comment by SlimF** [comment]
> 
> 
> I don't believe the streams mod works with shaders, as the last time I had it installed, it wasn't rendering properly

It works with some shaders (can't think of any at the moment, sorry) out of the box, but for most it requires you to put the IDs of Stream's water blocks into the shader's block.properties file. It should work the same for FutureMC, but for some reason it didn't work. That was most definitely a mistake on my end.

**Comment by thedarkcolour** [comment]
It's up to the shader author to add supported blocks for their shaders.
