### ISSUE TITLE
Suggestion: Additional Biome Whitelist for Bee Hive Generation

### ISSUE THREAD

**Issue by TeetoKaziim** [thedarkcolour/Future-MC#62]
Many biome mods add "plainslike" or "flower forest like" biomes that would be appropriate for bee hive spawning, but right now, having such mods in your game makes finding bees super rare, because a lot of the places where "plains" would show up get taken up by "meadow" or "grassland", or "flats" or similar "variants" that "technically" do not count for the bees.

A whitelist would at least let players / packmakers work around this by typing in the `modname:biome_name` ID of a biome to enable generation in that area.

Thanks for your time and consideration :D

**Comment by thedarkcolour** [comment]
I'll add it next update
