### ISSUE TITLE
smoker CT method wrong name or wiki typo

### ISSUE THREAD

**Issue by WarlordWossman** [thedarkcolour/Future-MC#63]
Just went through the wiki here on GH and for removing recipes from the smoker the naming is either very weird of potentially a typo:

![fmc](https://user-images.githubusercontent.com/16925725/66711101-a8cdbe80-ed85-11e9-8ee2-cd8aab87848e.PNG)

addValidItem and addValidInput nearly sound the same, I am assuming the the bottom one (in the red box) should be removeValidInput, similar to how it's worded for the blast furnace!

**Comment by thedarkcolour** [comment]
I noticed this when I was updating the Wiki. Check back, it should have all the correct functions there.

**Comment by WarlordWossman** [comment]
There is still something wrong with the names, I think you would want addRecipe for the smoker as well if you check the page now it still says addValidItem where it says addRecipe for the blast furnace instead.

**Comment by thedarkcolour** [comment]
God damnit
I wrote the whole thing and it didn't save.

**Comment by thedarkcolour** [comment]
It's actually fixed now. Sorry I'm just tired
