### ISSUE TITLE
blastfurnace/smoker picks furnace recipes before any CT changes

### ISSUE THREAD

**Issue by WarlordWossman** [thedarkcolour/Future-MC#65]
Since you can only black or whitelist inputs I am having trouble getting furnace recipes that exist in vanilla that I changed to show up properly. Or is this a matter of removing them and re-adding them so it can pick up the new recipe I defined in my other CT script files?

**Comment by WarlordWossman** [comment]
If I may add a suggestion to this: It might be easier and more flexible to just handle the blast furnace / smoker as its own device alltogether, that way the few recipes that need to be backed in can be removed and you can define entirely custom ones without the need of also having the same recipe in the vanilla furnace

**Comment by thedarkcolour** [comment]
There are new script functions for the Blast Furnace and smoker. You no longer whitelist/blacklist things, they have their own recipes now.

**Comment by thedarkcolour** [comment]
I just forgot to update the functions on the Wiki, check back for the new ones.
