### ISSUE TITLE
grindstone disenchanting issues

### ISSUE THREAD

**Issue by WarlordWossman** [thedarkcolour/Future-MC#66]
You can put 2 enchanted books in the 2 slots and when you grab the output book it consumes both. Not sure how one would solve this if both slots should work for disenchanting and repairing but it doesn't feel right to lose the item if you do it with books.

**Comment by WarlordWossman** [comment]
With Charm you also got enchanted books stacking to 16 so if you manage to make it only pull 1 item from 1 slot that would be amazing.

**Comment by thedarkcolour** [comment]
I'll fix next update.
