### ISSUE TITLE
disabling blastfurnace/smoker/campfire in cfg doesn't remove their recipes/JEI  tab

### ISSUE THREAD

**Issue by WarlordWossman** [thedarkcolour/Future-MC#67]
After testing around with them for a while I decided to toggle them off for using the mods config file but their JEI tabs and seemingly the recipes still get displayed.
Maybe I could fix that by removing all their recipes but ideally if you toggle those features off in the config their recipes and JEI tabs should disappear on their own.

**Comment by thedarkcolour** [comment]
I'll fix it.
