### ISSUE TITLE
slab recipes in stonecutter give 1 slab instead of 2

### ISSUE THREAD

**Issue by WarlordWossman** [thedarkcolour/Future-MC#69]
This makes the stonecutter only half as efficient at crafting slabs compared to the crafting table.
Just checked the wiki in vanilla you also get 2 slabs per block, should be an easy fix I assume!

Oh and very minor note: Think the config for it still says is decorative only, even if that might be an artefact left from previous updates.

**Comment by thedarkcolour** [comment]
I'll fix it. Until then I think you can re-add the recipes. Have you seen the JEI recipes button in the stonecutter gui? What do you think about its placement?

**Comment by WarlordWossman** [comment]
I saw the button for the recipes, it's neat to have one in the GUI.
Not too sure on its placement, it doesn't seem too important to me as long as it works :D

**Comment by Federsavo** [comment]
I think the button would be better if it had a 'J' in the texture

**Comment by thedarkcolour** [comment]
Fixed in 1.12.2 Alpha 0.2.01
