### ISSUE TITLE
blast furnace CT issues

### ISSUE THREAD

**Issue by WarlordWossman** [thedarkcolour/Future-MC#72]
Seems like I cannot remove recipes from the blast furnace with the "removeRecipe" method, it always shows the default recipes for the ores, even if they don't seem to be accurate. I changed redstone ore and lapis ore to give 4 pieces in the vanilla furnace (using CT as well), and somehow the blast furnace seems to grab this recipe, even if JEI displays the default and I tried to remove all recipes with redstone/lapis ore as inputs.

Might apply to smoker too, I kinda gave up testing for now since it's very confusing.

**Comment by thedarkcolour** [comment]
JEI is confusing on my end too, it's really hard to track down what causes this.

**Comment by alex-fantastico** [comment]
Can't remove recipes from Campfire, either.

**Comment by thedarkcolour** [comment]
I think I messed up Campfire recipe removal. It'll be fixed next update.
