### ISSUE TITLE
Misc. Suggestions / Ideas

### ISSUE THREAD

**Issue by SextupleTap** [thedarkcolour/Future-MC#75]
These are some more minor / niche things:
- In the recent 1.15 snapshots honey blocks won't stick to slime blocks anymore, I imagine this was already planned for a later on FutureMC update but I'm mentioning it just in case. Although, I would like to extend this a bit further just to bring up the idea of being compatible with other sticky type blocks such as quarks colored slime and tinkers constructs slime blocks, which also don't stick to each other / to slime as to be compatible with that and or other mods that would add similar blocks. (Perhaps specifying blocks in a config?)

- Drinking the Bottle of Honey gives saturation and hunger appropriately, but mods that add visual hunger and saturation displays in tool tips (such as Quark or Apple Skin) don't actually render anything, having this compatibility would be great.

- For the Globe banner pattern, I can find it when using the additional banners mod as an existing banner in the creative tab the mod creates, yet when using a mod like Just Enough Banners to view all banner patterns and their respective item, there is nothing for the Globe pattern, I'm just wondering as to when a method of obtaining it will be implemented or if it already exists and what it is. 

- Are the implementations of the 1.13+ "player holding and throwing" trident models possible?

- Is it possible to have a config option to disable individual block functionalities so that you can have it exist as a decorative block only? (e.g. the Stone Cutter was given functionality, yet you can no longer use it 'only decoratively' because of its GUI interface, this config addition would mainly be for Mod Pack purposes)

**Comment by thedarkcolour** [comment]
I have to explore if honey blocks not sticking to honey is possible.
Honey bottle is an easy fix.
Globe banner pattern is going to be released with the Loom functionality. I’m not sure the state of 0.1.13, but I if you create a file called “debug_future_mc.txt” in the root of your Minecraft directory that you can see the progress I have made with the loom. It also adds the globe pattern.
Trident models have been a long time request, but I haven’t figured out how to do those yet. I have a guess though, and it will come out next update if I manage to figure it out.
I could add the config option for block functionality next update.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thedarkcolour** [comment]
It turns out that the Honey blocks not sticking to slime blocks requires a coremod. I have an idea to fix the current issues with the Loom, but I'm not sure if they'll actually work. I have an idea for my Trident models that also requires a coremod because the IBakedModel approach is too confusing to me, and I just need to change the TEISR so a coremod will be much easier.
Basically, I'm gonna be depending on coremods more.

**Comment by SokyranTheDragon** [comment]
Quark implements colored slime blocks which aren't sticking to each other, and it provides interface `INonSticky` with a method `canStickToBlock`.

If you would add Quark as optional dependency, then it would allow you to implement Honey blocks not sticking to slime without having to work on a core mod for it (although it would require Quark to work). Besides less work, another benefit of this solution would be a guarantee of compatibility with slime blocks added by Quark.

I'm assuming you'd have to implement that interface and method with Optional annotation.


Quark source code reference: [INonSticky interface](https://github.com/Vazkii/Quark/blob/1.12/src/main/java/vazkii/quark/api/INonSticky.java), [BlockColorSlime](https://github.com/Vazkii/Quark/blob/1.12/src/main/java/vazkii/quark/automation/block/BlockColorSlime.java#L109)

**Comment by thedarkcolour** [comment]
That's actually what I did. I just bundled Quark's piston handling into Future MC so that everything works properly. I have fixed all these (except Trident model) in Future 0.2.1, which will be coming out later today.

**Comment by thedarkcolour** [comment]
I have actually found a solution to the Trident model, but it won't be coming in today's update.
