### ISSUE TITLE
Shift Clicking Stonecutter Items crashes game

### ISSUE THREAD

**Issue by SirSquidly** [thedarkcolour/Future-MC#78]
Exactly as it says in title, if the player uses the stonecutter gui, places and selects a block, and holds shift as they click the result, it crashes the game.

Here's the crash report:
[crash-2019-11-05_08.49.25-client.txt](https://github.com/thedarkcolour/Future-MC/files/3810200/crash-2019-11-05_08.49.25-client.txt)

**Comment by thedarkcolour** [comment]
Fixed in Alpha 0.2.01
