### ISSUE TITLE
Removing Stoncutter recipes Via Crafttweaker doesn't work

### ISSUE THREAD

**Issue by SirSquidly** [thedarkcolour/Future-MC#79]
removeAllOutputsForInput and clearRecipes don't seem to remove any recipes, as they still appear in the Stonecutter and in JEI's guis.

**Comment by thedarkcolour** [comment]
I’m going to fix in next update

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by slinkybass** [comment]
Any update? Thanks!

**Comment by thedarkcolour** [comment]
The update hasn't come out yet
