### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by vaggelis1234** [thedarkcolour/Future-MC#81]
Hi!
I am from Taiwan.
I have translated Traditional Chinese and Simplified Chinese for you. (Future MC)
This translation is my first translation module and I hope to be adopted.
Download:https://drive.google.com/open?id=1u_oZmFybLU3nQRpON7zSsFPVC2i23b7J

(Translation may not be perfect, I am using 19w46b for translation)

**Comment by thedarkcolour** [comment]
I will not support Chinese. I do not like seeing my mod reposted onto Chinese forums.

**Comment by vaggelis1234** [comment]
I won't post it on any forum,
Why don't you want to support Chinese?
