### ISSUE TITLE
[1.12.2] Trident bounces on snow

### ISSUE THREAD

**Issue by Soyuz247** [thedarkcolour/Future-MC#84]
So everytime i launch the trident onto a snow layer or a snow block, either the game crashes or the trident just start vibrantly glitching

**Comment by yezhiyi9670** [comment]
I have a similar bug: If a trident is launched onto a block with a top bounding box actually smaller than the model (soul sand, snow layers), the trident will glitch (it shakes and keeps making `Trident: Impact` sound), but in my case the game will not crash.

**Comment by thedarkcolour** [comment]
If you have a crash...
PLEASE
post the crash log.

**Comment by thedarkcolour** [comment]
Doesn't happen anymore with new trident.
