### ISSUE TITLE
Conflict with iguana tweaks* (FoamFix)

### ISSUE THREAD

**Issue by Pseudohuman93** [thedarkcolour/Future-MC#9]
There seems to be an issue mentioned in the title:

- https://paste.dimdev.org/elebolumum.mccrash

**Comment by thedarkcolour** [comment]
It is not a conflict with Iguana's Tweaks, it is a conflict with FoamFix. I have seen this issue before and have not had enough information to solve it, so thanks for entire crash log!

**Comment by thedarkcolour** [comment]
It is similar to #3 where FoamFix breaks my blockstate somehow.

**Comment by Pseudohuman93** [comment]
that's the latest version of FoamFix for 1.12.2 (with the latest version of Forge too)

**Comment by thedarkcolour** [comment]
What did you do to cause the crash?

**Comment by Pseudohuman93** [comment]
Just start minecraft. That's what I did.

I tried to start the game and it crashed

**Comment by thedarkcolour** [comment]
Ah. I'll release a fix with the new Composter block tomorrow.

**Comment by thedarkcolour** [comment]
Fixed in 0.1.5

**Comment by thedarkcolour** [comment]
I finally got it to reproduce, and I fixed it! Thanks for your help.
