### ISSUE TITLE
Make flowers supported by bees modifiable from other mods (without CraftTweaker)

### ISSUE THREAD

**Issue by SokyranTheDragon** [thedarkcolour/Future-MC#91]
I'm currently working on a mod that adds compatibility between several mods (including minor stuff like that), and that would be a rather convenient feature.

**Comment by thedarkcolour** [comment]
I'll make some changes.

**Comment by thedarkcolour** [comment]
You will be able to access a list of Pair<Block, Int> for block and metadata in `EntityBee.Companion.getFLOWERS()`

**Comment by thedarkcolour** [comment]
I've changed it to use ``BeeEntity.FLOWERS``, a list of IBlockState. Check it out in Alpha 0.2.01 with sources
