### ISSUE TITLE
Make crops growable by bees modifiable

### ISSUE THREAD

**Issue by SokyranTheDragon** [thedarkcolour/Future-MC#92]
I'm assuming CraftTweaker integration, but being able to modify it from other mods would be a neat additions too.

That might require changing the code a little bit, trying to make it as most compatible as possible. One way I've resolved it myself is using this code (will require changing to Kotlin):

```java
Optional<IProperty<?>> ageProperty = block.getDefaultState().getPropertyKeys().stream().filter(property -> property.getName().equals("age")).findAny();
ageProperty.ifPresent(property -> this.ageProperty = property);
```

which would find you the property named `age`. One note about that though, I've noticed that ExtraUtilities mod is using property named `growth` instead.

**Comment by thedarkcolour** [comment]
I'll see if it makes sense to add more compatibility. I don't think Extra Utilities would be an issue because  most of their plants don't seem growable by bees.

**Comment by thedarkcolour** [comment]
Compatibility is coming soon.

**Comment by thedarkcolour** [comment]
You can check ``thedarkcolour.futuremc.api.BeePollinationHandler`` for more information
