### ISSUE TITLE
Bee Crash

### ISSUE THREAD

**Issue by GuerreroCraft61** [thedarkcolour/Future-MC#95]
Spawn Bee crash the server
`08.02 20:00:30 [Server] Server thread/ERROR Encountered an unexpected exception
08.02 20:00:30 [Server] INFO net.minecraft.util.ReportedException: Ticking entity
08.02 20:00:30 [Server] INFO at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
08.02 20:00:30 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
08.02 20:00:30 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block futureminecraf:beenest, it is not an allowed value
08.02 20:00:30 [Server] INFO at pl.asie.foamfix.common.FoamyBlockState.withProperty(FoamyBlockState.java:59) ~[foamfix-0.10.10-1.12.2.jar:?]
08.02 20:00:30 [Server] INFO at net.mcreator.futureminecraf.MCreatorBeenest$BlockCustom.getStateFromMeta(MCreatorBeenest.java:72) ~[MCreatorBeenest$BlockCustom.class:?]
08.02 20:00:30 [Server] INFO at thedarkcolour.futuremc.entity.bee.EntityBee$AITempt.isTempting(EntityBee.java:996) ~[EntityBee$AITempt.class:?]
08.02 20:00:30 [Server] INFO at thedarkcolour.futuremc.entity.bee.EntityBee$AITempt.shouldExecute(EntityBee.java:990) ~[EntityBee$AITempt.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:94) ~[xf.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763) ~[vq.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359) ~[vp.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577) ~[vq.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178) ~[vd.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43) ~[zv.class:?]
08.02 20:00:30 [Server] INFO at thedarkcolour.futuremc.entity.bee.EntityBee.onLivingUpdate(EntityBee.java:327) ~[EntityBee.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) ~[vp.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295) ~[vq.class:?]
08.02 20:00:30 [Server] INFO at thedarkcolour.futuremc.entity.bee.EntityBee.onUpdate(EntityBee.java:216) ~[EntityBee.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) ~[amu.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.world.World.updateEntity(World.java:1958) ~[amu.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.world.World.redirect$updateEntity$zzj000(World.java:4123) ~[amu.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.world.World.updateEntities(World.java:1762) ~[amu.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
08.02 20:00:30 [Server] INFO at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
08.02 20:00:30 [Server] INFO ... 4 more`

**Comment by thedarkcolour** [comment]
Send entire log through pastebin or hastebin

**Comment by thedarkcolour** [comment]
This is an issue with Future Versions, an MCreator mod.
