### ISSUE TITLE
[1.12.2] Loyalty is glitchy

### ISSUE THREAD

**Issue by yezhiyi9670** [thedarkcolour/Future-MC#98]
When I throw a trident with Loyalty III (in survival mode), the trident plays the sound `Trident: Loyalty` after a while but just stays there instead of returning to me. I can still go to the place where it landed and pick it up. But the code indicated that it will return to the player after a short time and add itself into the player's inventory.

I am using Forge 14.23.5.2847 with Optifine HD U F6_pre1 (without any other mods). If this is a bug of Forge or Optifine, please let me know.

**Comment by yezhiyi9670** [comment]
The trident will return after it finishes glitching if it's shot onto a block which causes it to glitch (however this rarely happen). The glitch refers to the one mentioned in #84.

**Comment by thedarkcolour** [comment]
I have to redo it. It's pretty messed up.

**Comment by SrBizco** [comment]
could you fix it?

**Comment by thedarkcolour** [comment]
No longer happens with new trident.
